window.KINECHECK_ACADEMY_CONFIG = Object.freeze({
  supabaseUrl: "https://eqhcdclyeoapmqtlduwf.supabase.co",
  supabaseAnonKey: "sb_publishable_FTwhDZYCF3zf7W9rB7bFwQ_rF9Y7OX_",
  courseKeyFunction: "course-key",
  supportEmail: "soporte.kinecheck@gmail.com",
  appSso: Object.freeze({
    enabled: true,
    baseUrl: "https://apps.kinecheck.cl",
    handoffType: "kinecheck-sso-v3-access-only",
    transport: "form-post",
    postPath: "/api/license/sso",
    routes: Object.freeze({
      "kinecheck-estudiante": "/sso.html?product=kinecheck-estudiante",
    }),
  }),
  courses: [
    {
      slug: "kinecheck-clinico",
      title: "Guía complementaria KineCheck Clínico",
      subtitle: "Revisión estructurada de seguridad, hipótesis, examen y reevaluación. No reemplaza la ficha clínica institucional.",
      productId: "8150019",
      icon: "CL",
      kind: "tool",
      audience: "Profesionales",
      status: "active",
      url: "../kinecheck-clinico-guia/?product=kinecheck-clinico&v=20260806-ecosystem3",
    },
    {
      slug: "kinecheck-clinico-curso",
      title: "KineCheck Clínico",
      subtitle: "Curso profesional de evaluación, seguridad y razonamiento musculoesquelético.",
      productId: "8150019",
      icon: "KC",
      kind: "course",
      audience: "Profesionales",
      modules: 10,
      status: "active",
      url: "../kinecheck-clinico-curso/?course=kinecheck-clinico-curso&v=20260806-ecosystem3",
    },
    {
      slug: "comunicacion-clinica",
      title: "Comunicación Clínica",
      subtitle: "El arte de comunicar en salud",
      productId: "8192814",
      icon: "CC",
      kind: "course",
      status: "active",
      url: "../comunicacion-clinica.html?course=comunicacion-clinica&v=20260806-ecosystem3",
    },
    {
      slug: "kinecheck-estudiante",
      title: "KineCheck Estudiante",
      subtitle: "Evaluación y razonamiento clínico educativo. Utiliza exclusivamente casos ficticios, simulados o debidamente anonimizados.",
      productId: "8154796",
      icon: "KE",
      kind: "application",
      status: "active",
      url: "https://apps.kinecheck.cl/sso.html?product=kinecheck-estudiante",
      ssoProduct: "kinecheck-estudiante",
    },
    {
      slug: "kinecheck-recupera",
      title: "KineCheck Recupera",
      subtitle: "Próximamente. No disponible para registrar información mientras se revisa privacidad y protección de datos.",
      productId: "8157431",
      icon: "KR",
      kind: "application",
      status: "preparing",
      url: "",
      ssoProduct: "",
    },
    {
      slug: "mas-alla-del-dolor",
      title: "Más allá del dolor",
      subtitle: "Evaluación MSK integral",
      productId: "8194777",
      icon: "MD",
      kind: "course",
      status: "active",
      url: "https://emmanuelkine.github.io/mas-alla-del-dolor/?course=mas-alla-del-dolor&v=20260806-ecosystem3",
    },
    {
      slug: "evidencia-aplicada",
      title: "KineCheck Evidencia Aplicada",
      subtitle: "Razonamiento clínico y aplicación crítica de la evidencia",
      productId: "8208817",
      icon: "EA",
      kind: "course",
      status: "active",
      url: "https://emmanuelkine.github.io/kinecheck-evidencia-aplicada/?v=20260806-ecosystem3",
    },
    {
      slug: "traumatologia-ortopedia-clinica",
      title: "Traumatología y Ortopedia Clínica",
      subtitle: "Del mecanismo lesional a la decisión clínica segura",
      productId: "8205453",
      icon: "TO",
      kind: "course",
      status: "active",
      url: "../traumatologia/?course=traumatologia-ortopedia-clinica&v=20260806-ecosystem3",
    },
    {
      slug: "ejercicio-terapeutico",
      title: "Ejercicio Terapéutico",
      subtitle: "Prescripción clínica FITT‑VP, seguridad, modalidades y progresión basadas en evidencia.",
      productId: "PROPIETARIO",
      icon: "ET",
      kind: "course",
      audience: "Profesionales y estudiantes",
      audienceKey: "professionals",
      audiences: ["professionals", "students"],
      modules: 5,
      lessons: 10,
      status: "active",
      url: "./ejercicio-terapeutico/",
    },
    {
      slug: "kinecheck-lab-clinico",
      title: "KineCheck Lab Clínico",
      subtitle: "Simulador de razonamiento y decisiones clínicas",
      productId: "PROPIETARIO",
      icon: "LB",
      kind: "tool",
      status: "preparing",
      url: "../lab/",
    },
  ],
});
