const {resources,cases,flagInfo}=window.KC_BANDERAS_DATA;
let activeFlag='Todas';
let activeScreen='home';
let favorites=new Set(JSON.parse(localStorage.getItem('kcFlagsFavs')||'[]'));
let caseIndex=0;

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function badgeClass(flag){return ({Red:'red',Yellow:'yellow',Orange:'orange',Blue:'blue',Black:'black'})[flag]||'green'}
function renderFlags(){document.getElementById('flagGrid').innerHTML=Object.entries(flagInfo).map(([key,v])=>`<button class="flag" data-flag="${key}" onclick="selectFlag('${key}')"><div class="flagHead"><div class="ico">${v[0]}</div><div class="name">${v[1]}</div></div><div class="desc">${v[2]}</div><div class="flagBar"></div></button>`).join('')}
function renderChips(){document.getElementById('chips').innerHTML=Object.keys(flagInfo).map(f=>`<button class="chip ${activeFlag===f?'active':''}" onclick="setFlag('${f}')">${flagInfo[f][0]} ${f}</button>`).join('')}
function buildFilters(){const types=[...new Set(resources.map(x=>x.type))].sort();document.getElementById('typeFilter').innerHTML='<option value="">Todos los tipos</option>'+types.map(x=>`<option>${esc(x)}</option>`).join('');const years=[...new Set(resources.map(x=>x.year))].sort((a,b)=>b-a);document.getElementById('yearFilter').innerHTML='<option value="">Todos los años</option>'+years.map(x=>`<option>${x}</option>`).join('')}
function resourceCard(r){return `<article class="card" id="res-${r.id}"><div class="topline"><div class="source">${esc(r.source)} · ${esc(r.flag)}</div><button class="fav" onclick="toggleFav('${r.id}')">${favorites.has(r.id)?'♥':'♡'}</button></div><h3>${esc(r.title)}</h3><div class="meta">${esc(r.type)} · ${r.year} · ${esc(r.topic)}</div><p class="summary">${esc(r.summary)}</p><div class="badges"><span class="badge ${badgeClass(r.flag)}">${esc(r.flag)} flag</span><span class="badge green">Aplicabilidad: ${esc(r.applicability)}</span><span class="badge green">${esc(r.badge)}</span></div><details><summary>Qué preguntar / profundizar</summary><div class="inside"><ul>${r.questions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></details><details><summary>Cómo llevarlo a la clínica</summary><div class="inside"><ul>${r.how.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></details><details><summary>Limitaciones / precauciones</summary><div class="inside"><ul>${r.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></details><div class="actions"><button class="primary" onclick="window.open('${r.url}','_blank','noopener')">Abrir fuente ↗</button><button class="secondary" onclick="toggleFav('${r.id}')">${favorites.has(r.id)?'Quitar favorito':'Guardar'}</button></div></article>`}
function renderLibrary(){const q=document.getElementById('globalSearch').value.toLowerCase().trim();const t=document.getElementById('typeFilter').value;const y=document.getElementById('yearFilter').value;let rows=resources.filter(r=>(activeFlag==='Todas'||r.flag===activeFlag)&&(!t||r.type===t)&&(!y||String(r.year)===y)&&(!q||[r.title,r.authors,r.journal,r.topic,r.summary,r.flag,r.source].join(' ').toLowerCase().includes(q)));document.getElementById('countLine').textContent=`${rows.length} resultados · ${activeFlag}`;document.getElementById('resourceList').innerHTML=rows.length?rows.map(resourceCard).join(''):'<div class="empty">No hay resultados con estos filtros.</div>';renderSaved();updateMetrics()}
function renderSaved(){const rows=resources.filter(r=>favorites.has(r.id));document.getElementById('savedList').innerHTML=rows.length?rows.map(resourceCard).join(''):'<div class="empty">Aún no guardas fichas. Toca ♡ en cualquier recurso.</div>'}
function toggleFav(id){favorites.has(id)?favorites.delete(id):favorites.add(id);localStorage.setItem('kcFlagsFavs',JSON.stringify([...favorites]));renderLibrary()}
function setFlag(f){activeFlag=f;renderChips();renderLibrary()}
function selectFlag(f){setFlag(f);showScreen('library')}
function showScreen(id){activeScreen=id;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));if(id==='saved')renderSaved();if(id==='cases')renderCase();window.scrollTo({top:0,behavior:'smooth'})}
function openResource(id){activeFlag='Todas';showScreen('library');renderChips();renderLibrary();setTimeout(()=>{const el=document.getElementById('res-'+id);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});el.style.outline='2px solid #176b5b';setTimeout(()=>el.style.outline='',1800)}},120)}
function renderCase(){const c=cases[caseIndex];document.getElementById('caseContainer').innerHTML=`<div class="caseHero"><div class="label">Caso ${caseIndex+1} de ${cases.length} · ${esc(c.flag)}</div><h3>${esc(c.title)}</h3><p>${esc(c.text)}</p><div class="miniTitle">¿Cuál es la mejor conducta educativa con estos datos?</div><div class="caseOptions">${c.options.map((o,i)=>`<button class="option" onclick="answerCase(${i},'${o[1]}')">${esc(o[0])}</button>`).join('')}</div><div class="suspicion"><div class="level low ${c.level==='low'?'on':''}">🟢 Bajo</div><div class="level mid ${c.level==='mid'?'on':''}">🟡 Intermedio</div><div class="level high ${c.level==='high'?'on':''}">🔴 Alto</div></div><div class="feedback" id="caseFeedback"></div></div>`}
function answerCase(i,kind){document.querySelectorAll('.option').forEach((b,n)=>b.classList.toggle('selected',n===i));const fb=document.getElementById('caseFeedback');fb.className='feedback show '+(kind==='good'?'good':'learn');fb.innerHTML=`<strong>${kind==='good'?'Buena decisión clínica':'Revisa el razonamiento'}</strong><br>${esc(cases[caseIndex].feedback)}`}
function nextCase(){caseIndex=(caseIndex+1)%cases.length;renderCase()}
function updateMetrics(){document.getElementById('metricResources').textContent=resources.length;document.getElementById('homeTotal').textContent=resources.length;document.getElementById('homeFav').textContent=favorites.size;document.getElementById('homeCases').textContent=cases.length}

document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen)));
document.getElementById('globalSearch').addEventListener('input',()=>{if(activeScreen!=='library')showScreen('library');renderLibrary()});document.getElementById('typeFilter').addEventListener('change',renderLibrary);document.getElementById('yearFilter').addEventListener('change',renderLibrary);
renderFlags();renderChips();buildFilters();renderLibrary();renderCase();updateMetrics();
