(function(){
'use strict';
var D=window.KC_DLP_DATA;if(!D){return;}
var app=document.getElementById('app');var KEY='kc_dlp_premium_v6';var state={m:0,l:0,done:{},view:'home',exam:{},caseStep:{}};
function load(){try{var x=localStorage.getItem(KEY);if(x){var y=JSON.parse(x);if(y&&y.done)state.done=y.done;if(y&&y.exam)state.exam=y.exam;}}catch(e){}}
function save(){try{localStorage.setItem(KEY,JSON.stringify({done:state.done,exam:state.exam}));}catch(e){}}
function el(tag,cls,html){var e=document.createElement(tag);if(cls)e.className=cls;if(typeof html!=='undefined')e.innerHTML=html;return e;}
function btn(txt,cls,fn){var b=el('button',cls,txt);b.type='button';b.onclick=fn;return b;}
function clear(){while(app.firstChild)app.removeChild(app.firstChild);}
function totalLessons(){var n=0,i;for(i=0;i<D.modules.length;i++)n+=D.modules[i].l.length;return n;}
function completed(){var n=0,k;for(k in state.done)if(state.done.hasOwnProperty(k)&&state.done[k])n++;return n;}
function pct(){return Math.round(completed()/totalLessons()*100);}
function top(shell,active){var t=el('div','top');var brand=el('div','brand','<div class="logo"></div><div class="words">KineCheck<small>Dolor lumbar · Evidence Trainer</small></div>');brand.onclick=home;t.appendChild(brand);var a=el('div','actions');a.appendChild(btn('⌂ Inicio','btn',home));t.appendChild(a);shell.appendChild(t);var nav=el('div','kc-nav');var items=[['Curso',home,'home'],['Evidencia',evidencePage,'evidence'],['Instrumentos',instrumentsPage,'tools'],['Atlas',atlasPage,'atlas'],['Casos',casesPage,'cases'],['Evaluación final',examPage,'exam']];for(var i=0;i<items.length;i++){(function(x){nav.appendChild(btn(x[0],active===x[2]?'active':'',x[1]));})(items[i]);}shell.appendChild(nav);}
function mobile(shell){var m=el('div','mobile');m.appendChild(btn('⌂ Inicio','',home));m.appendChild(btn('▶ Continuar','',resume));m.appendChild(btn('▦ Instrumentos','',instrumentsPage));shell.appendChild(m);}
function shellBase(active){clear();var s=el('main','shell');top(s,active);app.appendChild(s);return s;}
function lessonId(mi,li){return mi+'-'+li;}
function firstPending(){for(var i=0;i<D.modules.length;i++)for(var j=0;j<D.modules[i].l.length;j++)if(!state.done[lessonId(i,j)])return{i:i,j:j};return null;}
function resume(){var p=firstPending();if(!p){openLesson(8,5);return;}openLesson(p.i,p.j);}
function home(){state.view='home';var s=shellBase('home');var hero=el('section','hero');var main=el('div','glass hero-main');main.innerHTML='<div class="eyebrow">● KineCheck · aplicación clínica basada en evidencia</div><h1>Dolor lumbar<br><span>persistente.</span></h1><p>Un entrenador de razonamiento clínico con 54 microlecciones, PROMs calculables, evidencia primaria enlazada, casos ramificados, atlas visual y evaluación final.</p>';var c=el('div','ctas');c.appendChild(btn(completed()?'Continuar curso →':'Comenzar curso →','primary',resume));c.appendChild(btn('Abrir instrumentos','btn',instrumentsPage));c.appendChild(btn('Resolver casos','btn',casesPage));main.appendChild(c);hero.appendChild(main);var side=el('aside','glass side');side.innerHTML='<div class="ring" style="--p:'+pct()+'"><b>'+pct()+'%</b><small>progreso</small></div><div class="metric"><strong>'+totalLessons()+'</strong><span>microlecciones</span></div><div class="metric"><strong>'+Object.keys(D.refs).length+'</strong><span>fuentes nucleares</span></div><div class="metric"><strong>'+D.scales.length+'</strong><span>instrumentos clínicos</span></div>';hero.appendChild(side);s.appendChild(hero);
var stats=el('div','statrow');stats.innerHTML='<div class="stat"><b>9</b><span>módulos clínicos</span></div><div class="stat"><b>'+D.cases.length+'</b><span>casos ramificados</span></div><div class="stat"><b>4</b><span>atlas interactivos</span></div><div class="stat"><b>10</b><span>preguntas de integración final</span></div>';s.appendChild(stats);
var hd=el('div','head','<div><h2>Ruta de aprendizaje</h2><p>Seis microlecciones por módulo. Cada una incluye una decisión clínica y evidencia vinculada.</p></div><span class="tag">'+completed()+'/'+totalLessons()+' completadas</span>');s.appendChild(hd);var grid=el('section','grid');for(var i=0;i<D.modules.length;i++){(function(mi){var m=D.modules[mi],n=0;for(var j=0;j<m.l.length;j++)if(state.done[lessonId(mi,j)])n++;var card=el('article','glass module');card.style.setProperty('--mc',m.c);card.innerHTML='<small>Módulo '+('0'+(mi+1)).slice(-2)+'</small><h3>'+m.t+'</h3><p>'+m.d+'</p><div class="lessoncount">'+m.l.length+' microlecciones</div><div class="mfoot"><div class="bar"><i style="width:'+(n/m.l.length*100)+'%"></i></div><span class="tag">'+n+'/'+m.l.length+'</span></div>';card.onclick=function(){openLesson(mi,0);};grid.appendChild(card);})(i);}s.appendChild(grid);
var hd2=el('div','head','<div><h2>Laboratorio clínico</h2><p>Herramientas para practicar decisiones y no solamente leer contenido.</p></div>');s.appendChild(hd2);var tools=el('section','tools');var ts=[['📚','Biblioteca científica','Artículos, autores y guías verificables.',evidencePage],['🧮','PROMs calculables','RMDQ, ODI, STarT Back, TSK-11, PCS y más.',instrumentsPage],['🧠','Casos ramificados','Decisiones con feedback razonado.',casesPage],['🫀','Atlas visual','Modelos interactivos originales.',atlasPage]];for(var q=0;q<ts.length;q++){(function(x){var t=el('article','glass tool','<div class="ico">'+x[0]+'</div><b>'+x[1]+'</b><p>'+x[2]+'</p>');t.onclick=x[3];tools.appendChild(t);})(ts[q]);}s.appendChild(tools);s.appendChild(el('div','foot','Preview educativo. No sustituye evaluación médica ni constituye un sistema diagnóstico. Las herramientas de cribado y PROMs deben interpretarse en contexto clínico y con la versión validada/licenciada correspondiente.'));mobile(s);window.scrollTo(0,0);}
function openLesson(mi,li){state.view='lesson';state.m=mi;state.l=li;var s=shellBase('home');var m=D.modules[mi],l=m.l[li];var course=el('div','course');var side=el('aside','glass sidebar');side.innerHTML='<div class="sidehead"><b>'+m.t+'</b><small>Módulo '+(mi+1)+' · '+m.l.length+' microlecciones</small></div>';for(var i=0;i<m.l.length;i++){(function(x){var link=el('div','lessonlink'+(x===li?' active':'')+(state.done[lessonId(mi,x)]?' done':''),'<div class="dot">'+(state.done[lessonId(mi,x)]?'✓':(x+1))+'</div><span>'+m.l[x].t+'</span>');link.onclick=function(){openLesson(mi,x);};side.appendChild(link);})(i);}course.appendChild(side);var lesson=el('article','glass lesson');lesson.innerHTML='<div class="crumb">Módulo '+(mi+1)+' · Microlección '+(li+1)+' de '+m.l.length+'</div><h1>'+l.t+'</h1><p class="lead">'+l.d+'</p>';
var goals=el('div','goals');var gs=['Comprender el concepto','Aplicarlo a una decisión','Vincularlo con evidencia'];for(i=0;i<3;i++)goals.appendChild(el('div','goal','<b>0'+(i+1)+'</b>'+gs[i]));lesson.appendChild(goals);
lesson.appendChild(conceptBlock(mi,li));lesson.appendChild(clinicalQuestion(l));lesson.appendChild(evidenceBlock(l.r));if(mi===1&&(li===1||li===3))lesson.appendChild(safetyBlock());if(mi===2&&li>=1&&li<=4){var jump=el('div','toolbox','<h3>Aplicación inmediata</h3><p>Esta microlección se conecta con los calculadores de instrumentos clínicos.</p>');jump.appendChild(btn('Abrir PROMs y calculadoras →','primary',instrumentsPage));lesson.appendChild(jump);}if(mi===8&&li===5){var ex=el('div','examcard','<h3>Evaluación final disponible</h3><p>Integra seguridad, PROMs, imagen, ejercicio, comunicación y seguimiento en 10 decisiones clínicas.</p>');ex.appendChild(btn('Ir a evaluación final →','primary',examPage));lesson.appendChild(ex);}
var nav=el('div','lessonnav');nav.appendChild(btn('← Anterior','btn',prevLesson));nav.appendChild(btn(state.done[lessonId(mi,li)]?'Siguiente →':'Completar y continuar →','primary',function(){state.done[lessonId(mi,li)]=true;save();nextLesson();}));lesson.appendChild(nav);course.appendChild(lesson);s.appendChild(course);mobile(s);window.scrollTo(0,0);}
function conceptBlock(mi,li){var box=el('section','block');var text=['Define la pregunta clínica antes de elegir herramientas.','Conecta el hallazgo con seguridad, función, comportamiento o capacidad.','Decide qué variable debería cambiar si tu hipótesis es correcta.'];if(mi===0&&li===4)text=['La imagen aporta información anatómica, pero no determina por sí sola la fuente del dolor.','La prevalencia de hallazgos degenerativos aumenta con la edad incluso en personas sin dolor.','Comunica la imagen sin ocultarla ni convertirla en una sentencia de fragilidad.'];if(mi===6)text=['Selecciona tareas relevantes para la persona, no ejercicios por tradición.','Gradúa una o más variables: rango, carga, volumen, velocidad, frecuencia o complejidad.','La progresión depende de respuesta, recuperación y objetivo funcional.'];box.innerHTML='<h2>Marco de razonamiento</h2><div class="callout" style="--cc:'+D.modules[mi].c+'"><b>1 · Pregunta</b>'+text[0]+'</div><div class="callout" style="--cc:'+D.modules[mi].c+';margin-top:8px"><b>2 · Interpretación</b>'+text[1]+'</div><div class="callout" style="--cc:'+D.modules[mi].c+';margin-top:8px"><b>3 · Reevaluación</b>'+text[2]+'</div>';return box;}
function clinicalQuestion(l){var q=l.q,w=el('section','clinicalq');if(!q){return w;}w.innerHTML='<div class="eyebrow">Decisión clínica progresiva</div><h3>'+q[0]+'</h3>';var fb=el('div','feedback','');for(var i=0;i<q[1].length;i++){(function(ix){var b=btn(String.fromCharCode(65+ix)+'. '+q[1][ix],'choice',function(){var bs=w.getElementsByTagName('button');for(var j=0;j<bs.length;j++)bs[j].disabled=true;if(ix===q[2]){b.className+=' correct';fb.className='feedback good';fb.innerHTML='Correcto. La respuesta mantiene el razonamiento contextual y vincula información con una decisión clínica.';}else{b.className+=' wrong';fb.className='feedback bad';fb.innerHTML='Revisa la lógica. Evita reglas automáticas, causalidad no demostrada y decisiones desconectadas de función o seguridad.';}});w.appendChild(b);})(i);}w.appendChild(fb);return w;}
function evidenceBlock(ids){var box=el('section','evidencebox');box.innerHTML='<h3>Evidencia vinculada a esta microlección</h3><p class="source-note">Abre la fuente original para revisar diseño, población, resultados y limitaciones.</p>';var grid=el('div','refgrid');for(var i=0;i<ids.length;i++){var r=D.refs[ids[i]];if(r)grid.appendChild(refCard(r));}box.appendChild(grid);return box;}
function refCard(r){var c=el('article','refcard');c.innerHTML='<h4>'+r.authors+' ('+r.year+')</h4><p>'+r.title+'</p><div class="refmeta"><span class="pill">'+r.type+'</span><span class="pill">'+r.quality+'</span></div><p>'+r.note+'</p><a class="reflink" target="_blank" rel="noopener" href="'+r.url+'">Abrir fuente original ↗</a>';return c;}
function safetyBlock(){var b=el('div','safealert','<b>Seguridad clínica:</b> si aparecen déficits neurológicos progresivos, alteración esfinteriana nueva, anestesia en silla de montar, combinación sugestiva de fractura, signos sistémicos o cualquier hallazgo que eleve de forma importante la sospecha de patología seria, la ruta musculoesquelética debe detenerse o adaptarse y escalarse la evaluación médica según urgencia.');return b;}
function nextLesson(){var m=state.m,l=state.l+1;if(l>=D.modules[m].l.length){m++;l=0;}if(m>=D.modules.length){home();return;}openLesson(m,l);}
function prevLesson(){var m=state.m,l=state.l-1;if(l<0){m--;if(m<0){home();return;}l=D.modules[m].l.length-1;}openLesson(m,l);}
function evidencePage(){state.view='evidence';var s=shellBase('evidence');s.appendChild(el('div','sectiontitle','<h1>Biblioteca científica</h1><p>Fuentes nucleares verificables, priorizando guías, revisiones sistemáticas, RCTs y validaciones de instrumentos.</p>'));var authors={};for(var k in D.refs){if(D.refs.hasOwnProperty(k)){var first=D.refs[k].authors.split(',')[0];authors[first]=1;}}var cloud=el('div','authorcloud');for(k in authors)if(authors.hasOwnProperty(k))cloud.appendChild(el('span','',k));s.appendChild(cloud);var tb=el('div','toolbar');var input=el('input','searchfield');input.placeholder='Buscar autor, artículo, instrumento o tema…';tb.appendChild(input);s.appendChild(tb);var grid=el('div','refgrid');function renderRefs(){while(grid.firstChild)grid.removeChild(grid.firstChild);var term=(input.value||'').toLowerCase();for(var id in D.refs)if(D.refs.hasOwnProperty(id)){var r=D.refs[id],hay=(r.authors+' '+r.title+' '+r.type+' '+r.quality+' '+r.note).toLowerCase();if(!term||hay.indexOf(term)>=0)grid.appendChild(refCard(r));}}input.oninput=renderRefs;renderRefs();s.appendChild(grid);s.appendChild(el('div','notice','Jerarquía editorial: una referencia prestigiosa no se convierte automáticamente en “verdad absoluta”. El curso enseña a revisar población, diseño, comparador, magnitud del efecto, incertidumbre y aplicabilidad clínica.'));mobile(s);window.scrollTo(0,0);}
function instrumentsPage(){state.view='tools';var s=shellBase('tools');s.appendChild(el('div','sectiontitle','<h1>Instrumentos y calculadoras</h1><p>Calcula puntuaciones sin copiar íntegramente cuestionarios protegidos. Usa siempre la versión validada/licenciada para la población correspondiente.</p>'));s.appendChild(el('div','safealert','<b>Regla de interpretación:</b> ningún PROM diagnostica por sí solo una lesión, una condición psicológica o la necesidad de derivación. Los resultados se integran con historia, examen, función y evolución.'));var grid=el('div','instrumentgrid');for(var i=0;i<D.scales.length;i++){(function(sc){var card=el('article','instrument');card.innerHTML='<h4>'+sc.name+'</h4><div class="refmeta"><span class="pill">'+sc.domain+'</span><span class="pill">'+sc.range+'</span></div><p>'+sc.direction+'</p><p>'+sc.validation+'</p><div class="notice">'+sc.copyright+'</div>';card.appendChild(btn('Abrir calculador','primary',function(){renderCalculator(sc,s);}));grid.appendChild(card);})(D.scales[i]);}s.appendChild(grid);var calc=el('div','toolbox');calc.id='calculatorHost';calc.innerHTML='<h3>Selecciona un instrumento</h3><p>El calculador aparecerá aquí.</p>';s.appendChild(calc);mobile(s);window.scrollTo(0,0);}
function renderCalculator(sc,shell){var host=document.getElementById('calculatorHost');while(host.firstChild)host.removeChild(host.firstChild);host.appendChild(el('h3','',sc.name));host.appendChild(el('p','',sc.domain+' · '+sc.range+' · '+sc.direction));var refs=evidenceBlock(sc.refs);host.appendChild(refs);var form=el('div','');var result=el('div','calcresult','Ingresa los valores para calcular.');host.appendChild(form);host.appendChild(result);
if(sc.kind==='rmdq'){var inp=numInput(0,24,'Ítems marcados (0–24)');form.appendChild(inp);form.appendChild(btn('Calcular RMDQ','primary',function(){var v=Number(inp.value);if(!valid(v,0,24)){result.innerHTML='Ingresa un valor entre 0 y 24.';return;}result.innerHTML='<strong>'+v+'/24</strong><br>Mayor puntaje indica mayor limitación funcional reportada. En Chile existe una versión culturalmente validada; interpreta el cambio longitudinal junto con metas y función.';}));}
else if(sc.kind==='odi'){var ins=scoreInputs(form,10,0,5,'Sección ','cols10',true);form.appendChild(btn('Calcular ODI','primary',function(){var sum=0,n=0;for(var i=0;i<ins.length;i++){if(ins[i].value!==''){var v=Number(ins[i].value);if(!valid(v,0,5)){result.innerHTML='Cada sección respondida debe estar entre 0 y 5.';return;}sum+=v;n++;}}if(!n){result.innerHTML='Completa al menos una sección.';return;}var p=Math.round((sum/(5*n))*1000)/10;result.innerHTML='<strong>'+p+'%</strong><br>'+n+' secciones respondidas. Fórmula: suma / (5 × secciones respondidas) × 100. Registra la versión del ODI y no imputes secciones omitidas como cero.';}));}
else if(sc.kind==='sbt'){var sb=scoreInputs(form,9,0,1,'Ítem ','cols9',false);form.appendChild(btn('Clasificar STarT Back','primary',function(){var vals=readAll(sb,0,1);if(!vals){result.innerHTML='Completa los 9 valores codificados como 0 o 1 usando el instrumento autorizado.';return;}var total=sum(vals),psych=vals[4]+vals[5]+vals[6]+vals[7]+vals[8],risk=total<=3?'Bajo':(psych>=4?'Alto':'Medio');result.innerHTML='<strong>'+risk+' riesgo</strong><br>Total '+total+'/9 · subescala psicosocial '+psych+'/5. Es una clasificación pronóstica; no es diagnóstico ni reemplaza el juicio clínico.';}));}
else if(sc.kind==='tsk11'){var tk=scoreInputs(form,11,1,4,'Ítem ','cols11',false);form.appendChild(btn('Calcular TSK-11','primary',function(){var vals=readAll(tk,1,4);if(!vals){result.innerHTML='Completa 11 valores entre 1 y 4.';return;}var v=sum(vals);result.innerHTML='<strong>'+v+'/44</strong><br>Rango 11–44; puntuaciones mayores reflejan más miedo relacionado con movimiento/relesión. TSK-11 no contiene ítems reversos en su puntuación habitual y no debe usarse como instrumento aislado.';}));}
else if(sc.kind==='pcs'){var pc=scoreInputs(form,13,0,4,'Ítem ','cols13',false);form.appendChild(btn('Calcular PCS','primary',function(){var vals=readAll(pc,0,4);if(!vals){result.innerHTML='Completa 13 valores entre 0 y 4.';return;}var v=sum(vals);result.innerHTML='<strong>'+v+'/52</strong><br>Mayor puntuación refleja mayor catastrofización reportada. Evita usar puntos de corte universales fuera de la población para la que fueron estudiados.';}));}
else if(sc.kind==='pseq'){var pq=scoreInputs(form,10,0,6,'Ítem ','cols10',false);form.appendChild(btn('Calcular PSEQ-10','primary',function(){var vals=readAll(pq,0,6);if(!vals){result.innerHTML='Completa 10 valores entre 0 y 6.';return;}var v=sum(vals);result.innerHTML='<strong>'+v+'/60</strong><br>Mayor puntuación indica mayor autoeficacia relacionada con funcionar a pesar del dolor. Interpreta el cambio dentro de la versión/población utilizada.';}));}
else if(sc.kind==='fabq'){var fq=scoreInputs(form,16,0,6,'Ítem ','cols16',false);form.appendChild(btn('Calcular FABQ','primary',function(){var vals=readAll(fq,0,6);if(!vals){result.innerHTML='Completa 16 valores entre 0 y 6.';return;}var pa=vals[1]+vals[2]+vals[3]+vals[4];var work=vals[5]+vals[6]+vals[8]+vals[9]+vals[10]+vals[11]+vals[14];result.innerHTML='<strong>Actividad física '+pa+'/24 · Trabajo '+work+'/42</strong><br>Se suman solo los ítems estándar de cada subescala. Registra la versión validada utilizada.';}));}
else if(sc.kind==='psfs'){var row=el('div','calcrow');var ps=[];for(var i=0;i<5;i++){var lab=el('label','','Actividad '+(i+1));var x=numInput(0,10,'0–10');lab.appendChild(x);row.appendChild(lab);ps.push(x);}form.appendChild(row);form.appendChild(btn('Calcular PSFS','primary',function(){var vals=[];for(var j=0;j<ps.length;j++)if(ps[j].value!==''){var v=Number(ps[j].value);if(!valid(v,0,10)){result.innerHTML='Los puntajes deben estar entre 0 y 10.';return;}vals.push(v);}if(!vals.length){result.innerHTML='Ingresa al menos una actividad.';return;}var av=Math.round(sum(vals)/vals.length*10)/10;result.innerHTML='<strong>Promedio '+av+'/10</strong><br>'+vals.length+' actividades registradas. Guarda además el nombre exacto de cada actividad y compárala longitudinalmente.';}));}
else if(sc.kind==='nprs'){var cur=numInput(0,10,'Dolor actual 0–10');var best=numInput(0,10,'Mejor 0–10');var worst=numInput(0,10,'Peor 0–10');form.appendChild(cur);form.appendChild(best);form.appendChild(worst);form.appendChild(btn('Resumir NPRS','primary',function(){var a=Number(cur.value),b=Number(best.value),c=Number(worst.value);if(!valid(a,0,10)||!valid(b,0,10)||!valid(c,0,10)){result.innerHTML='Completa los tres valores entre 0 y 10.';return;}result.innerHTML='<strong>Actual '+a+'/10</strong><br>Mejor '+b+'/10 · peor '+c+'/10 · rango '+(c-b)+'. Interpreta junto a función, confianza, sueño y participación.';}));}
host.scrollIntoView({behavior:'smooth',block:'start'});}
function numInput(min,max,placeholder){var x=el('input','singleinput');x.type='number';x.min=min;x.max=max;x.step='1';x.placeholder=placeholder;return x;}
function scoreInputs(form,n,min,max,prefix,cls,allowBlank){var row=el('div','calcrow '+cls),arr=[];for(var i=0;i<n;i++){var lab=el('label','',prefix+(i+1));var x=el('input','');x.type='number';x.min=min;x.max=max;x.step='1';if(!allowBlank)x.placeholder=min+'–'+max;lab.appendChild(x);row.appendChild(lab);arr.push(x);}form.appendChild(row);return arr;}
function valid(v,min,max){return !isNaN(v)&&v>=min&&v<=max;}
function readAll(ins,min,max){var vals=[];for(var i=0;i<ins.length;i++){if(ins[i].value==='')return null;var v=Number(ins[i].value);if(!valid(v,min,max))return null;vals.push(v);}return vals;}
function sum(a){var s=0;for(var i=0;i<a.length;i++)s+=a[i];return s;}
function atlasPage(){state.view='atlas';var s=shellBase('atlas');s.appendChild(el('div','sectiontitle','<h1>Atlas visual interactivo</h1><p>Ilustraciones vectoriales originales KineCheck para explicar conceptos sin depender de imágenes comerciales.</p>'));var grid=el('div','atlasgrid');var items=[['Columna y contexto',svgSpine(),'La anatomía importa, pero el significado clínico emerge al integrar síntomas, función y contexto.'],['Modelo biopsicosocial',svgBps(),'Los dominios se superponen; no son compartimentos ni una dicotomía físico/psicológico.'],['Exposición progresiva',svgExposure(),'La dificultad se gradúa para recuperar opciones, confianza y tolerancia.'],['Ciclo clínico',svgLoop(),'Evaluar → intervenir → medir → ajustar mantiene el razonamiento verificable.']];for(var i=0;i<items.length;i++){var c=el('article','atlascard','<div class="atlasviz">'+items[i][1]+'</div><h4>'+items[i][0]+'</h4><p>'+items[i][2]+'</p>');grid.appendChild(c);}s.appendChild(grid);mobile(s);window.scrollTo(0,0);}
function svgSpine(){return '<svg viewBox="0 0 600 330" aria-label="Columna lumbar estilizada"><defs><linearGradient id="g1" x1="0" x2="1"><stop stop-color="#55e6ce"/><stop offset="1" stop-color="#7c73ff"/></linearGradient></defs><g transform="translate(250 30)"><rect x="55" y="5" width="70" height="38" rx="14" fill="url(#g1)"/><rect x="50" y="58" width="80" height="42" rx="14" fill="url(#g1)" opacity=".92"/><rect x="45" y="116" width="90" height="45" rx="15" fill="url(#g1)" opacity=".84"/><rect x="40" y="177" width="100" height="48" rx="16" fill="url(#g1)" opacity=".76"/><rect x="35" y="242" width="110" height="52" rx="17" fill="url(#g1)" opacity=".68"/><g fill="#0a1428"><rect x="65" y="45" width="50" height="9" rx="4"/><rect x="62" y="103" width="56" height="9" rx="4"/><rect x="59" y="164" width="62" height="9" rx="4"/><rect x="56" y="228" width="68" height="9" rx="4"/></g></g><g stroke="#ffb85c" stroke-width="5" fill="none" stroke-linecap="round"><path d="M120 90 C180 70 210 80 250 120"/><path d="M480 220 C420 250 390 250 350 230"/></g><text x="25" y="70" fill="#dfe7f6" font-size="18">Carga</text><text x="462" y="205" fill="#dfe7f6" font-size="18">Contexto</text></svg>';}
function svgBps(){return '<svg viewBox="0 0 600 330"><circle cx="245" cy="150" r="105" fill="#55e6ce" opacity=".28"/><circle cx="355" cy="150" r="105" fill="#ff6fae" opacity=".25"/><circle cx="300" cy="235" r="105" fill="#7c73ff" opacity=".28"/><text x="150" y="115" fill="white" font-size="20">Biología</text><text x="365" y="115" fill="white" font-size="20">Psicología</text><text x="270" y="290" fill="white" font-size="20">Social</text><text x="247" y="180" fill="#fff" font-size="25" font-weight="700">Persona</text></svg>';}
function svgExposure(){return '<svg viewBox="0 0 600 330"><g fill="#182747" stroke="#6cc8ff" stroke-width="2"><rect x="50" y="245" width="95" height="45" rx="10"/><rect x="155" y="205" width="95" height="85" rx="10"/><rect x="260" y="160" width="95" height="130" rx="10"/><rect x="365" y="105" width="95" height="185" rx="10"/><rect x="470" y="45" width="80" height="245" rx="10"/></g><g fill="#dfe7f6" font-size="15"><text x="75" y="273">Tolerable</text><text x="177" y="235">Rango</text><text x="286" y="190">Carga</text><text x="388" y="135">Volumen</text><text x="485" y="75">Tarea real</text></g><path d="M70 220 C180 170 270 125 500 20" stroke="#55e6ce" stroke-width="6" fill="none" stroke-linecap="round"/></svg>';}
function svgLoop(){return '<svg viewBox="0 0 600 330"><defs><marker id="a" markerWidth="10" markerHeight="10" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#55e6ce"/></marker></defs><g fill="#12213e" stroke="#7c73ff" stroke-width="2"><rect x="55" y="125" width="120" height="70" rx="18"/><rect x="240" y="45" width="120" height="70" rx="18"/><rect x="425" y="125" width="120" height="70" rx="18"/><rect x="240" y="225" width="120" height="70" rx="18"/></g><g fill="white" font-size="18"><text x="82" y="168">Evaluar</text><text x="265" y="88">Intervenir</text><text x="458" y="168">Medir</text><text x="267" y="268">Ajustar</text></g><g stroke="#55e6ce" stroke-width="5" fill="none" marker-end="url(#a)"><path d="M175 140 C205 90 215 80 240 78"/><path d="M360 78 C400 88 420 105 435 130"/><path d="M500 195 C470 235 430 255 360 260"/><path d="M240 260 C170 245 130 215 110 195"/></g></svg>';}
function casesPage(){state.view='cases';var s=shellBase('cases');s.appendChild(el('div','sectiontitle','<h1>Casos clínicos ramificados</h1><p>Cada decisión modifica el recorrido y entrega feedback basado en seguridad, función y evidencia.</p>'));var grid=el('div','casegrid');for(var i=0;i<D.cases.length;i++){(function(c){var card=el('article','casecard','<h4>'+c.name+'</h4><p>'+c.intro+'</p><div class="refmeta"><span class="pill">'+c.steps.length+' decisiones</span></div>');card.appendChild(btn('Resolver caso →','primary',function(){renderCase(c,s);}));grid.appendChild(card);})(D.cases[i]);}s.appendChild(grid);var host=el('div','casebranch');host.id='caseHost';host.innerHTML='<h3>Selecciona un caso</h3><p>El recorrido aparecerá aquí.</p>';s.appendChild(host);mobile(s);window.scrollTo(0,0);}
function renderCase(c,shell){var host=document.getElementById('caseHost');while(host.firstChild)host.removeChild(host.firstChild);var ix=0,path=[];function step(){while(host.firstChild)host.removeChild(host.firstChild);host.appendChild(el('h3','',c.name));host.appendChild(el('p','',c.intro));var p=el('div','casepath');for(var z=0;z<path.length;z++)p.appendChild(el('span','',path[z]));host.appendChild(p);if(ix>=c.steps.length){host.appendChild(el('div','casefeedback','Caso completado. La decisión final debe documentar hipótesis, seguridad, variables de seguimiento y criterio de progresión/derivación.'));host.appendChild(btn('Volver a casos','primary',casesPage));return;}var st=c.steps[ix];host.appendChild(el('h4','',st.q));var fb=el('div','casefeedback','Selecciona una opción.');for(var i=0;i<st.o.length;i++){(function(k){host.appendChild(btn(String.fromCharCode(65+k)+'. '+st.o[k],'casechoice',function(){if(k===st.a){fb.innerHTML='<b>Decisión defendible.</b> '+st.fb;path.push('Paso '+(ix+1)+' ✓');}else{fb.innerHTML='<b>Decisión débil.</b> '+st.fb;path.push('Paso '+(ix+1)+' revisar');}var bs=host.getElementsByTagName('button');for(var j=0;j<bs.length;j++)bs[j].disabled=true;var next=btn('Continuar →','primary',function(){ix++;step();});fb.appendChild(document.createElement('br'));fb.appendChild(next);}));})(i);}host.appendChild(fb);host.scrollIntoView({behavior:'smooth',block:'start'});}step();}
function examPage(){state.view='exam';var s=shellBase('exam');s.appendChild(el('div','sectiontitle','<h1>Evaluación final basada en casos</h1><p>10 decisiones de integración. Umbral de dominio formativo sugerido: 80%. No equivale a certificación clínica ni licencia profesional.</p>'));var prog=el('div','progressline','<i style="width:'+examAnswered()/D.exam.length*100+'%"></i>');s.appendChild(prog);var host=el('div','');for(var i=0;i<D.exam.length;i++){(function(ix){var q=D.exam[ix],card=el('section','examcard');card.innerHTML='<div class="crumb">Pregunta '+(ix+1)+' de '+D.exam.length+'</div><h3>'+q.q+'</h3>';for(var j=0;j<q.o.length;j++){(function(k){var b=btn(String.fromCharCode(65+k)+'. '+q.o[k],'examopt'+(state.exam[ix]===k?' selected':''),function(){state.exam[ix]=k;save();examPage();});card.appendChild(b);})(j);}host.appendChild(card);})(i);}s.appendChild(host);s.appendChild(btn('Calcular resultado final','primary',function(){showExamResult(s);}));mobile(s);window.scrollTo(0,0);}
function examAnswered(){var n=0;for(var i=0;i<D.exam.length;i++)if(typeof state.exam[i]==='number')n++;return n;}
function showExamResult(s){if(examAnswered()<D.exam.length){alert('Responde las 10 preguntas antes de calcular el resultado.');return;}var ok=0;for(var i=0;i<D.exam.length;i++)if(state.exam[i]===D.exam[i].a)ok++;var p=Math.round(ok/D.exam.length*100);var box=el('div','examresult','<h2>'+p+'% · '+ok+'/'+D.exam.length+'</h2><p>'+(p>=80?'Dominio formativo alcanzado en esta versión.':'Conviene revisar las decisiones con evidencia antes de repetir la evaluación.')+'</p>');var weak=[];for(i=0;i<D.exam.length;i++)if(state.exam[i]!==D.exam[i].a)weak.push(i);if(weak.length){box.appendChild(el('h4','','Revisar evidencia de las preguntas falladas'));var grid=el('div','refgrid');var seen={};for(i=0;i<weak.length;i++){var rr=D.exam[weak[i]].r;for(var j=0;j<rr.length;j++)if(!seen[rr[j]]&&D.refs[rr[j]]){seen[rr[j]]=1;grid.appendChild(refCard(D.refs[rr[j]]));}}box.appendChild(grid);}box.appendChild(btn('Reiniciar evaluación','btn',function(){state.exam={};save();examPage();}));s.appendChild(box);box.scrollIntoView({behavior:'smooth'});}
load();home();
})();