window.KC_DLP_DATA=(function(){
var refs={
WHO23:{id:'WHO23',authors:'World Health Organization',year:2023,title:'WHO guideline for non-surgical management of chronic primary low back pain in adults in primary and community care settings',type:'Guía clínica internacional',quality:'Guía OMS',url:'https://www.who.int/publications/i/item/9789240081789',note:'Marco de cuidado holístico, centrado en la persona y selección de intervenciones no quirúrgicas.'},
GEORGE21:{id:'GEORGE21',authors:'George SZ, Fritz JM, Silfies SP, et al.',year:2021,title:'Interventions for the Management of Acute and Chronic Low Back Pain: Revision 2021',type:'Clinical Practice Guideline',quality:'JOSPT / APTA',url:'https://pubmed.ncbi.nlm.nih.gov/34719942/',note:'Recomendaciones sobre ejercicio, educación, terapia manual y clasificación clínica.'},
HARTVIGSEN18:{id:'HARTVIGSEN18',authors:'Hartvigsen J, Hancock MJ, Kongsted A, et al.',year:2018,title:'What low back pain is and why we need to pay attention',type:'Revisión / Lancet Series',quality:'The Lancet',url:'https://pubmed.ncbi.nlm.nih.gov/29573870/',note:'Carga global, curso, heterogeneidad y necesidad de un enfoque biopsicosocial.'},
FOSTER18:{id:'FOSTER18',authors:'Foster NE, Anema JR, Cherkin D, et al.',year:2018,title:'Prevention and treatment of low back pain: evidence, challenges, and promising directions',type:'Revisión / Lancet Series',quality:'The Lancet',url:'https://pubmed.ncbi.nlm.nih.gov/29573872/',note:'Síntesis de tratamientos, sobreutilización y oportunidades de mejora.'},
MAHER17:{id:'MAHER17',authors:'Maher C, Underwood M, Buchbinder R',year:2017,title:'Non-specific low back pain',type:'Review',quality:'The Lancet',url:'https://pubmed.ncbi.nlm.nih.gov/27745712/',note:'Panorama clínico del dolor lumbar inespecífico y su manejo.'},
BRINJIKJI15:{id:'BRINJIKJI15',authors:'Brinjikji W, Luetmer PH, Comstock B, et al.',year:2015,title:'Systematic literature review of imaging features of spinal degeneration in asymptomatic populations',type:'Revisión sistemática',quality:'AJNR',url:'https://pubmed.ncbi.nlm.nih.gov/25430861/',note:'Alta prevalencia de hallazgos degenerativos en personas asintomáticas y aumento con la edad.'},
DOWNIE13:{id:'DOWNIE13',authors:'Downie A, Williams CM, Henschke N, et al.',year:2013,title:'Red flags to screen for malignancy and fracture in patients with low back pain',type:'Revisión sistemática',quality:'BMJ',url:'https://pubmed.ncbi.nlm.nih.gov/24335669/',note:'Muchas banderas aisladas cambian poco la probabilidad; algunas combinaciones son más informativas.'},
HAN23:{id:'HAN23',authors:'Han CS, Hancock MJ, Downie A, et al.',year:2023,title:'Red flags to screen for vertebral fracture in people presenting with low back pain',type:'Revisión Cochrane',quality:'Cochrane',url:'https://pubmed.ncbi.nlm.nih.gov/37615643/',note:'Actualización sobre precisión diagnóstica de banderas para fractura vertebral.'},
HAYDEN21:{id:'HAYDEN21',authors:'Hayden JA, Ellis J, Ogilvie R, Malmivaara A, van Tulder MW',year:2021,title:'Exercise therapy for chronic low back pain',type:'Revisión sistemática y metaanálisis',quality:'Cochrane',url:'https://pubmed.ncbi.nlm.nih.gov/34580864/',note:'Ejercicio mejora dolor y función frente a varios comparadores, con heterogeneidad entre programas.'},
HO22:{id:'HO22',authors:'Ho EKY, Chen L, Simic M, et al.',year:2022,title:'Psychological interventions for chronic, non-specific low back pain: systematic review with network meta-analysis',type:'Revisión sistemática y network meta-analysis',quality:'BMJ',url:'https://pubmed.ncbi.nlm.nih.gov/35354560/',note:'Intervenciones psicológicas pueden añadir beneficio, especialmente junto a fisioterapia estructurada.'},
KENT23:{id:'KENT23',authors:'Kent P, Haines T, O\'Sullivan P, et al.',year:2023,title:'Cognitive functional therapy with or without movement sensor biofeedback versus usual care for chronic, disabling low back pain (RESTORE)',type:'RCT fase 3',quality:'The Lancet',url:'https://pubmed.ncbi.nlm.nih.gov/37146623/',note:'Ensayo pragmático de terapia funcional cognitiva en dolor lumbar crónico incapacitante.'},
HANCOCK25:{id:'HANCOCK25',authors:'Hancock M, Smith A, O\'Sullivan P, et al.',year:2025,title:'Cognitive functional therapy ... RESTORE: 3-year follow-up',type:'Seguimiento de RCT',quality:'Lancet Rheumatology',url:'https://pubmed.ncbi.nlm.nih.gov/40780241/',note:'Seguimiento prolongado del ensayo RESTORE.'},
GUIC14:{id:'GUIC14',authors:'Guic E, Galdames S, Rebolledo P',year:2014,title:'Validation and cultural adaptation of the Chilean version of the Roland-Morris Disability Questionnaire',type:'Estudio de validación',quality:'Revista Médica de Chile',url:'https://pubmed.ncbi.nlm.nih.gov/25327316/',note:'Validación cultural chilena del RMDQ de 24 ítems y una versión abreviada de 6 ítems.'},
KOVACS02:{id:'KOVACS02',authors:'Kovacs FM, Llobera J, Gil Del Real MT, et al.',year:2002,title:'Validation of the Spanish version of the Roland-Morris questionnaire',type:'Estudio de validación',quality:'Spine',url:'https://pubmed.ncbi.nlm.nih.gov/11880841/',note:'Validación española del Roland-Morris.'},
FAIRBANK00:{id:'FAIRBANK00',authors:'Fairbank JCT, Pynsent PB',year:2000,title:'The Oswestry Disability Index',type:'Revisión clinimétrica',quality:'Spine',url:'https://pubmed.ncbi.nlm.nih.gov/11074683/',note:'Revisión de versiones, validación y uso del ODI.'},
SELVA19:{id:'SELVA19',authors:'Selva-Sevilla C, Ferrara P, Gerónimo-Pardo M',year:2019,title:'Psychometric Properties of the Spanish Version of the Oswestry Disability Index',type:'Estudio de propiedades psicométricas',quality:'Spine',url:'https://pubmed.ncbi.nlm.nih.gov/30234803/',note:'Propiedades psicométricas de versión española en población con cirugía lumbar previa.'},
HILL08:{id:'HILL08',authors:'Hill JC, Dunn KM, Lewis M, et al.',year:2008,title:'A primary care back pain screening tool: identifying patient subgroups for initial treatment',type:'Desarrollo y validación pronóstica',quality:'Arthritis & Rheumatism',url:'https://pubmed.ncbi.nlm.nih.gov/18438893/',note:'Desarrollo del STarT Back Screening Tool de 9 ítems.'},
HILL11:{id:'HILL11',authors:'Hill JC, Whitehurst DGT, Lewis M, et al.',year:2011,title:'Comparison of stratified primary care management for low back pain with current best practice (STarT Back)',type:'Randomised controlled trial',quality:'The Lancet',url:'https://pubmed.ncbi.nlm.nih.gov/21963002/',note:'Ensayo de atención estratificada según riesgo pronóstico.'},
GOMEZ11:{id:'GOMEZ11',authors:'Gómez-Pérez L, López-Martínez AE, Ruiz-Párraga GT',year:2011,title:'Psychometric Properties of the Spanish Version of the Tampa Scale for Kinesiophobia',type:'Estudio de validación',quality:'Journal of Pain',url:'https://pubmed.ncbi.nlm.nih.gov/20926355/',note:'Versión española; análisis derivó una estructura de 11 ítems con buena fiabilidad y validez.'},
ALPALHAO24:{id:'ALPALHAO24',authors:'Alpalhão V, et al.',year:2024,title:'Are the Cross-Culturally Adapted Versions of the Tampa Scale for Kinesiophobia 11-Item Valid, Reliable, and Responsive?',type:'Revisión sistemática COSMIN',quality:'Journal of Pain',url:'https://pubmed.ncbi.nlm.nih.gov/38866123/',note:'Revisión crítica de propiedades de medición del TSK-11 en múltiples idiomas.'},
GARCIA08:{id:'GARCIA08',authors:'García Campayo J, Rodero B, Alda M, et al.',year:2008,title:'Validation of the Spanish version of the Pain Catastrophizing Scale in fibromyalgia',type:'Estudio de validación',quality:'Medicina Clínica',url:'https://pubmed.ncbi.nlm.nih.gov/19007576/',note:'Versión española del PCS con estructura de tres factores.'}
};
function L(t,d,r,q){return{t:t,d:d,r:r||[],q:q||null};}
var modules=[
{t:'Reencuadrar el dolor lumbar',c:'#55e6ce',d:'Carga, curso, contexto, imagenología y objetivos centrados en la persona.',l:[
L('Por qué importa el dolor lumbar','Carga global, discapacidad y heterogeneidad clínica obligan a evitar soluciones únicas.',['HARTVIGSEN18','WHO23'],['¿Qué cambia primero al reconocer la heterogeneidad?',['Buscar una técnica universal','Construir hipótesis individualizadas','Solicitar imagen a todos'],1]),
L('Dolor lumbar inespecífico','La ausencia de una causa única identificable no equivale a ausencia de problema ni a falta de rigor clínico.',['MAHER17','HARTVIGSEN18'],['¿Qué significa “inespecífico”?',['Que el dolor es imaginario','Que no se identifica una única patología específica que explique el cuadro','Que no necesita evaluación'],1]),
L('Modelo biopsicosocial aplicado','Factores biológicos, psicológicos y sociales interactúan y deben traducirse a decisiones clínicas concretas.',['WHO23','HARTVIGSEN18'],['¿Cuál es el error más frecuente del enfoque biopsicosocial?',['Integrar dominios','Usarlo como lista sin cambiar conducta clínica','Explorar función'],1]),
L('Curso, recurrencia y trayectorias','Una fotografía de hoy no reemplaza la línea de tiempo: episodios, mejorías, recaídas y contexto importan.',['HARTVIGSEN18'],['¿Qué dato aporta más al curso?',['Solo EVA actual','Patrón temporal y función entre episodios','Una única prueba especial'],1]),
L('Imagenología sin alarmismo','Hallazgos degenerativos son frecuentes en asintomáticos y deben interpretarse en contexto clínico.',['BRINJIKJI15'],['¿Qué implica un hallazgo degenerativo aislado?',['Demuestra causa del dolor','Debe contextualizarse y no establece causalidad por sí solo','Obliga a reposo'],1]),
L('Objetivos centrados en la persona','El resultado relevante incluye función, participación, confianza y metas, no solamente intensidad de dolor.',['WHO23','FOSTER18'],['¿Cuál es una meta clínica mejor formulada?',['Dolor 0/10','Volver a cargar a su hijo y caminar 30 minutos con confianza','Normalizar una imagen'],1])]},
{t:'Historia, pronóstico y riesgo',c:'#6cc8ff',d:'Anamnesis dirigida, triage, banderas y riesgo pronóstico.',l:[
L('Entrevista que genera hipótesis','La anamnesis debe organizar seguridad, función, expectativas, evolución y preguntas a resolver.',['GEORGE21','WHO23'],['¿Qué debe producir la entrevista?',['Una lista extensa de síntomas','Hipótesis y prioridades','Un diagnóstico por imagen'],1]),
L('Triage y patología seria','Las banderas se interpretan en combinación con prevalencia, historia y examen; varias aisladas tienen utilidad limitada.',['DOWNIE13','HAN23'],['¿Cómo usar una bandera roja?',['Como diagnóstico automático','Como modificador de probabilidad dentro del contexto','Ignorarla si el dolor es leve'],1]),
L('Fractura vertebral: razonamiento probabilístico','Edad, trauma y uso prolongado de corticoides pueden aumentar la sospecha, especialmente en combinación.',['HAN23','DOWNIE13'],['¿Qué aumenta más la utilidad clínica?',['Una bandera inespecífica aislada','Combinaciones coherentes con historia y examen','Solo intensidad de dolor'],1]),
L('Síntomas neurológicos y urgencia','Déficits motores progresivos, alteraciones esfinterianas nuevas o anestesia en silla de montar requieren escalamiento médico urgente.',['GEORGE21'],['¿Qué hallazgo cambia inmediatamente la ruta?',['Rigidez matinal leve','Déficit motor progresivo con alteración esfinteriana nueva','Dolor 5/10 estable'],1]),
L('Pronóstico: riesgo no es destino','Factores pronósticos modifican probabilidad y deben orientar seguimiento, no etiquetar a la persona.',['HILL08','HILL11'],['¿Qué significa riesgo alto?',['Que el mal resultado es inevitable','Que conviene intensificar evaluación de barreras y seguimiento','Que se debe evitar actividad'],1]),
L('STarT Back con cautela','Es una herramienta pronóstica de 9 ítems con clasificación bajo/medio/alto; no es diagnóstico ni sustituto del razonamiento.',['HILL08','HILL11'],['¿Cuál es su función principal?',['Diagnosticar una lesión','Estratificar riesgo pronóstico','Medir fuerza lumbar'],1])]},
{t:'Evaluación estructurada',c:'#7c73ff',d:'PROMs, línea basal, examen físico y síntesis reproducible.',l:[
L('Arquitectura de evaluación','Entrevista → PROMs → observación → examen dirigido → síntesis → plan de reevaluación.',['GEORGE21','WHO23'],['¿Por qué secuenciar?',['Para usar más pruebas','Para que cada etapa responda preguntas','Para evitar PROMs'],1]),
L('RMDQ: función lumbar','Roland-Morris mide limitación funcional asociada al dolor lumbar; existe versión validada en Chile.',['GUIC14','KOVACS02'],['¿Qué ventaja tiene en Chile?',['Es un diagnóstico','Existe adaptación cultural chilena publicada','Reemplaza examen físico'],1]),
L('ODI: discapacidad relacionada con columna','El ODI es un PROM clásico de 10 secciones; su puntuación debe manejar respuestas omitidas correctamente.',['FAIRBANK00','SELVA19'],['¿Qué error evitar?',['Registrar versión usada','Calcular porcentaje como si todas las secciones estuvieran respondidas cuando faltan datos','Reevaluar'],1]),
L('PSFS: función individualizada','La Patient-Specific Functional Scale permite seguir actividades relevantes seleccionadas por la propia persona.',['WHO23'],['¿Qué aporta PSFS?',['Un diagnóstico estructural','Seguimiento de tareas significativas individuales','Una bandera roja'],1]),
L('NPRS y dolor','La escala numérica 0–10 es útil para intensidad, pero no debe convertirse en el único resultado.',['GEORGE21'],['¿Qué debe acompañar al dolor?',['Función y participación','Solo otra escala de dolor','Siempre imagen'],0]),
L('Examen físico con propósito','Movimiento, capacidad, neurología y pruebas específicas se seleccionan según la hipótesis y deben cambiar decisiones.',['GEORGE21'],['¿Cuándo vale una prueba?',['Cuando es sofisticada','Cuando modifica hipótesis, seguridad, dosificación o seguimiento','Cuando confirma siempre tejido'],1])]},
{t:'Razonamiento y clasificación',c:'#ffb85c',d:'Niveles de análisis, sensibilidad, mecanismos y síntesis clínica.',l:[
L('Local, regional y global','Amplía el foco cuando una explicación local no alcanza: región lumbar, segmentos relacionados y contexto global.',['WHO23','HARTVIGSEN18'],['¿Qué evita este modelo?',['Integración','Reduccionismo local','Reevaluación'],1]),
L('Dolor y nocicepción no son sinónimos','El dolor es una experiencia influida por múltiples procesos; su intensidad no cuantifica directamente daño tisular.',['HARTVIGSEN18'],['¿Qué afirmación es más precisa?',['Más dolor = más daño siempre','Dolor y daño no mantienen una relación lineal universal','El tejido nunca importa'],1]),
L('Sensibilidad y modulación','Persistencia puede acompañarse de cambios en sensibilidad y protección; la explicación debe evitar fragilizar.',['HO22','WHO23'],['¿Qué lenguaje es preferible?',['Su espalda está desgastada','Su sistema puede estar más protector y podemos graduar exposición','No tiene nada'],1]),
L('Diferencial y exclusión razonada','El razonamiento integra patrón clínico, neurología, sistémicos, trauma y evolución para decidir si seguir o derivar.',['GEORGE21','DOWNIE13'],['¿Qué es una buena exclusión?',['Checklist sin contexto','Hipótesis alternativas ponderadas por probabilidad y hallazgos','Una prueba aislada negativa'],1]),
L('Síntesis operativa','Una hipótesis clínica útil debe explicar limitación actual, variables modificables y cómo comprobar si el plan funciona.',['GEORGE21'],['¿Qué debe generar una hipótesis?',['Solo una etiqueta','Una intervención y criterio de reevaluación','Más pruebas por rutina'],1]),
L('Reevaluación como parte del razonamiento','Si el cambio esperado no ocurre, revisa seguridad, hipótesis, dosis, adherencia, barreras y metas.',['WHO23','GEORGE21'],['¿Qué hacer ante falta de progreso?',['Repetir igual indefinidamente','Revisar hipótesis y variables modificables','Culpar adherencia'],1])]},
{t:'Dolor persistente y conducta',c:'#ff6fae',d:'Miedo, evitación, catastrofización, autoeficacia, sueño y lenguaje.',l:[
L('Miedo relacionado con movimiento','La kinesiofobia puede influir en actividad y discapacidad; se mide, pero no se diagnostica por intuición.',['GOMEZ11','ALPALHAO24'],['¿Cómo identificar miedo?',['Inferirlo por postura','Preguntarlo y medirlo cuando sea relevante','Asumirlo si duele mucho'],1]),
L('TSK-11','Versión breve de 11 ítems; mayor puntuación refleja más miedo de movimiento relacionado con dolor.',['GOMEZ11','ALPALHAO24'],['¿Qué no puede hacer TSK-11?',['Cuantificar miedo relacionado con movimiento','Diagnosticar por sí sola un trastorno psicológico','Apoyar seguimiento'],1]),
L('Catastrofización','Rumiar, magnificar y sentirse indefenso ante dolor puede asociarse con peores resultados; el PCS permite cuantificar este constructo.',['GARCIA08','HO22'],['¿Cómo usar PCS?',['Como etiqueta de personalidad','Como PROM contextual para orientar conversación y seguimiento','Como criterio único de alta'],1]),
L('Autoeficacia','La confianza en poder funcionar a pesar del dolor es una variable clínica relevante para objetivos y exposición.',['HO22'],['¿Qué intervención puede apoyarla?',['Experiencias graduadas de éxito','Reposo indefinido','Mensajes de fragilidad'],0]),
L('Sueño, estrés y carga total','El contexto de recuperación modifica tolerancia y participación; debe integrarse sin atribuir todo el dolor a “estrés”.',['WHO23'],['¿Cuál es el equilibrio correcto?',['Todo es psicológico','Ignorar sueño y estrés','Integrarlos junto a factores físicos y sociales'],2]),
L('Lenguaje que no fragiliza','Comunicar incertidumbre, normalizar variabilidad y evitar metáforas de daño irreversible puede disminuir amenaza innecesaria.',['WHO23','BRINJIKJI15'],['¿Qué mensaje es preferible?',['Tiene la espalda de una persona de 80 años','La imagen muestra cambios frecuentes con la edad; veamos si encajan con su cuadro','Nunca vuelva a flexionarse'],1])]},
{t:'Comunicación y educación',c:'#55e6ce',d:'Alianza, expectativas, educación activa, imagen y decisiones compartidas.',l:[
L('Alianza terapéutica','Escuchar, validar y acordar metas no es “extra”; forma parte del tratamiento centrado en la persona.',['WHO23'],['¿Qué define una buena alianza?',['Imponer el plan','Compartir decisiones y metas','Evitar preguntas'],1]),
L('Expectativas y pronóstico comunicado','Explora qué espera la persona y evita promesas absolutas; explica incertidumbre y plan de seguimiento.',['WHO23'],['¿Qué es reasegurar?',['Prometer curación','Explicar qué sabemos, qué vigilamos y qué puede hacer la persona','Minimizar dolor'],1]),
L('Educación que cambia conducta','La educación es más útil cuando se conecta con una acción y se comprueba comprensión.',['HO22','WHO23'],['¿Qué técnica mejora comprensión?',['Monólogo largo','Teach-back','Entregar un PDF sin conversación'],1]),
L('Comunicar imagenología','La imagen se integra con síntomas y examen; hallazgos frecuentes en asintomáticos deben contextualizarse.',['BRINJIKJI15'],['¿Qué evita alarmismo?',['Ocultar la imagen','Explicar prevalencia y relevancia clínica','Nombrar “desgaste irreversible”'],1]),
L('Metas SMART con sentido clínico','Las metas deben ser específicas y funcionales, pero seguir conectadas con valores y roles relevantes.',['WHO23'],['¿Qué meta es mejor?',['Ser más fuerte','Subir dos pisos para volver al trabajo sin detenerse en 4 semanas','Mejorar RM'],1]),
L('Plan compartido y autonomía','La persona debe saber qué hacer, cómo progresar, qué esperar y cuándo consultar si aparecen señales de alarma.',['WHO23','GEORGE21'],['¿Qué indica autonomía?',['Depender de terapia presencial para moverse','Contar con plan de acción, progresión y criterios de consulta','Evitar actividad sin supervisión'],1])]},
{t:'Intervención activa',c:'#70e3a2',d:'Ejercicio, exposición, capacidad, adherencia y retorno funcional.',l:[
L('Ejercicio: qué dice la evidencia','El ejercicio es una opción recomendada; los efectos promedio varían y no existe una modalidad universalmente superior.',['HAYDEN21','WHO23','GEORGE21'],['¿Qué conclusión es más adecuada?',['Existe un ejercicio mágico','Seleccionar ejercicio según objetivos, preferencias y respuesta','Ejercicio no sirve'],1]),
L('Dosificar para una tarea real','Rango, carga, volumen, velocidad, frecuencia y complejidad son variables que pueden graduarse.',['GEORGE21'],['¿Qué define dosis?',['Solo repeticiones','Conjunto de variables de carga y exposición','Solo dolor durante ejercicio'],1]),
L('Fuerza y capacidad','Aumentar capacidad física puede ampliar opciones funcionales; el programa debe ser progresivo y relevante.',['HAYDEN21'],['¿Qué es progresión?',['Subir carga siempre','Aumentar desafío según tolerancia y objetivo','Esperar dolor cero'],1]),
L('Exposición progresiva','Si existe miedo, una jerarquía de tareas puede crear experiencias de seguridad y recuperar participación.',['HO22','KENT23'],['¿Qué orden es razonable?',['De la tarea más temida al máximo','De tareas tolerables a más desafiantes con reevaluación','Evitar la tarea'],1]),
L('Actividad aeróbica y condición global','La condición física global puede formar parte del plan cuando conecta con objetivos y tolerancia.',['WHO23','HAYDEN21'],['¿Por qué incluirla?',['Porque cura discos','Porque puede mejorar capacidad y salud global','Porque reemplaza fuerza siempre'],1]),
L('Adherencia y entorno','El mejor programa teórico falla si no cabe en tiempo, recursos, preferencias y contexto de la persona.',['WHO23'],['¿Qué programa suele ser más viable?',['El más complejo','El que la persona puede realizar y progresar','El que requiere equipamiento inaccesible'],1])]},
{t:'Terapias y dosificación',c:'#ffb85c',d:'Adjuntos, psicología, multimodalidad, flare-ups y límites del rol.',l:[
L('Terapia manual como adjunto','Puede utilizarse como parte del manejo, pero no debería reforzar dependencia ni reemplazar actividad.',['WHO23','GEORGE21'],['¿Cuál es un uso coherente?',['Corregir vértebras desplazadas','Facilitar movimiento y conectar con actividad','Aplicarla indefinidamente'],1]),
L('Intervenciones psicológicas','CBT, educación y otras estrategias pueden añadir beneficio cuando se integran con cuidado físico estructurado.',['HO22'],['¿Qué dice la evidencia de red?',['Psicología siempre reemplaza fisioterapia','Suele ser más efectiva integrada con fisioterapia','No tiene rol'],1]),
L('Cognitive Functional Therapy','RESTORE evaluó una intervención individualizada que integra comprensión, exposición y cambio de conducta en dolor lumbar incapacitante.',['KENT23','HANCOCK25'],['¿Qué evita una lectura errónea?',['Convertir CFT en protocolo rígido','Entenderla como intervención individualizada','Usarla sin evaluación'],1]),
L('Flare-up: plan anticipado','Un aumento transitorio de síntomas no siempre significa daño; un plan previo puede reducir respuestas de miedo y abandono.',['WHO23'],['¿Qué debe incluir?',['Reposo absoluto automático','Ajuste temporal, criterios de alarma y retorno progresivo','Suspender para siempre'],1]),
L('Medicamentos y alcance profesional','La guía OMS incluye recomendaciones farmacológicas, pero la prescripción corresponde al profesional habilitado; el kinesiólogo debe coordinar y derivar cuando corresponda.',['WHO23'],['¿Qué es correcto en este curso?',['Indicar dosis farmacológicas','Reconocer uso, efectos y necesidad de coordinación sin prescribir fuera del alcance','Suspender medicación'],1]),
L('Reevaluar dosis y respuesta','Mantener, progresar, reducir o cambiar depende de respuesta, recuperación, adherencia y metas.',['GEORGE21','WHO23'],['¿Qué dato manda la progresión?',['Una regla fija','Respuesta clínica y función en contexto','Solo edad'],1])]},
{t:'Integración clínica',c:'#7c73ff',d:'Ruta de 11 pasos, documentación, casos y evaluación final.',l:[
L('Ruta de 11 pasos','Integra cuidado centrado en persona, seguridad, pronóstico, examen, PROMs, educación, ejercicio, adjuntos, dosis y retorno.',['WHO23','GEORGE21'],['¿Qué caracteriza la ruta?',['Secuencia rígida','Marco flexible y reevaluable','Checklist diagnóstico'],1]),
L('Caso A: miedo a flexión e imagen','Integra imagenología, kinesiofobia, exposición y retorno funcional sin invalidar síntomas.',['BRINJIKJI15','GOMEZ11','KENT23'],['¿Qué priorizar?',['Prohibir flexión','Seguridad, significado del dolor, metas y exposición graduada','Manipulación diaria'],1]),
L('Caso B: riesgo y derivación','Combina antecedentes, banderas y examen para decidir cuándo detener la ruta musculoesquelética y escalar atención.',['DOWNIE13','HAN23','GEORGE21'],['¿Qué cambia la ruta?',['Hallazgos coherentes con patología seria o déficit progresivo','Dolor mecánico estable','Miedo al movimiento aislado'],0]),
L('Documentación clínica útil','Registra hipótesis, hallazgos que cambian conducta, PROMs, dosis, respuesta y plan de reevaluación.',['GEORGE21'],['¿Qué sobra en una nota?',['Datos que cambian decisiones','Listas extensas sin interpretación','Criterios de reevaluación'],1]),
L('Caso C: retorno al trabajo','Integra demandas laborales, capacidad, PSFS, autoeficacia y progresión específica de tareas.',['WHO23','HAYDEN21'],['¿Qué es específico?',['Fortalecer core genérico','Progresar tareas que reproducen demandas reales con medición','Reposo'],1]),
L('Evaluación final','Resolver casos exige justificar seguridad, elección de PROMs, intervención, progresión y seguimiento con evidencia.',['WHO23','GEORGE21','HAYDEN21'],['¿Qué se evalúa?',['Memoria de autores solamente','Razonamiento clínico aplicado','Capacidad de nombrar técnicas'],1])]}];
var scales=[
{id:'RMDQ',name:'Roland-Morris Disability Questionnaire',domain:'Limitación funcional por dolor lumbar',range:'0–24',direction:'Mayor puntaje = mayor limitación',validation:'Versión chilena validada: Guic, Galdames & Rebolledo (2014).',refs:['GUIC14','KOVACS02'],kind:'rmdq',copyright:'No se reproducen aquí los 24 enunciados; el calculador recibe el número de ítems marcados.'},
{id:'ODI',name:'Oswestry Disability Index',domain:'Discapacidad relacionada con columna',range:'0–100%',direction:'Mayor porcentaje = mayor discapacidad reportada',validation:'Existen versiones españolas y múltiples estudios psicométricos.',refs:['FAIRBANK00','SELVA19'],kind:'odi',copyright:'Se ingresan puntajes de sección (0–5) sin reproducir el texto del instrumento.'},
{id:'SBT',name:'STarT Back Screening Tool',domain:'Riesgo de discapacidad persistente',range:'Total 0–9; subescala psicosocial 0–5',direction:'Clasificación bajo / medio / alto',validation:'Desarrollo y validación original en atención primaria; herramienta pronóstica, no diagnóstica.',refs:['HILL08','HILL11'],kind:'sbt',copyright:'No se reproducen los ítems; para uso comercial debe revisarse la licencia correspondiente.'},
{id:'TSK11',name:'Tampa Scale for Kinesiophobia – 11',domain:'Miedo relacionado con movimiento/relesión',range:'11–44',direction:'Mayor puntaje = mayor miedo relacionado con movimiento',validation:'Versión española validada; revisión COSMIN 2024 recomienda no usarla como instrumento aislado.',refs:['GOMEZ11','ALPALHAO24'],kind:'tsk11',copyright:'Se calculan respuestas codificadas 1–4; no se reproducen los enunciados.'},
{id:'PCS',name:'Pain Catastrophizing Scale',domain:'Catastrofización relacionada con dolor',range:'0–52',direction:'Mayor puntaje = mayor catastrofización',validation:'Versión española validada en dolor crónico; interpretar según población.',refs:['GARCIA08'],kind:'pcs',copyright:'Se ingresan 13 puntajes 0–4; no se reproducen los ítems.'},
{id:'PSEQ',name:'Pain Self-Efficacy Questionnaire – 10',domain:'Autoeficacia frente al dolor',range:'0–60',direction:'Mayor puntaje = mayor autoeficacia',validation:'PROM ampliamente utilizado; usar versión validada para el idioma/población correspondiente.',refs:['HO22'],kind:'pseq',copyright:'Calculador numérico sin reproducción de ítems.'},
{id:'FABQ',name:'Fear-Avoidance Beliefs Questionnaire',domain:'Creencias de miedo-evitación',range:'Actividad física 0–24; Trabajo 0–42',direction:'Mayor puntaje = mayores creencias de miedo-evitación',validation:'Usar versión validada y registrar subescala.',refs:['HO22'],kind:'fabq',copyright:'Calculador por número de ítem; no reproduce enunciados.'},
{id:'PSFS',name:'Patient-Specific Functional Scale',domain:'Función específica del paciente',range:'0–10 por actividad',direction:'Mayor puntaje = mayor capacidad percibida',validation:'Útil para metas individualizadas y seguimiento funcional.',refs:['WHO23'],kind:'psfs',copyright:'Se ingresan actividades y puntajes definidos por la persona.'},
{id:'NPRS',name:'Numeric Pain Rating Scale',domain:'Intensidad de dolor',range:'0–10',direction:'Mayor puntaje = mayor intensidad',validation:'Debe combinarse con función, participación y otros dominios relevantes.',refs:['GEORGE21'],kind:'nprs',copyright:'Escala numérica simple.'}
];
var cases=[
{id:'flexion',name:'Caso 1 · Flexión, miedo e imagen',intro:'42 años, dolor lumbar persistente 14 meses. RM previa con “degeneración discal”. Evita flexionarse y dejó de jugar con su hijo. Sin síntomas sistémicos ni déficit neurológico.',steps:[
{q:'Primera decisión',o:['Explicar que la RM confirma desgaste doloroso','Confirmar seguridad, explorar significado de la RM y definir meta funcional','Indicar reposo de flexión 6 semanas'],a:1,fb:'La prioridad es seguridad + significado + función. La imagen aislada no establece causalidad.'},
{q:'PROM más útil para complementar',o:['TSK-11 y PSFS','Solo NPRS','Ninguno'],a:0,fb:'Miedo relacionado con movimiento y función específica conectan con el problema planteado.'},
{q:'Intervención inicial',o:['Exposición graduada a flexión/tareas significativas con educación y progresión','Evitar flexión hasta dolor 0','Terapia pasiva exclusiva'],a:0,fb:'La exposición se gradúa según tolerancia, meta y respuesta, sin asumir que dolor equivale a daño.'}]},
{id:'redflag',name:'Caso 2 · Cambio de ruta',intro:'68 años, dolor lumbar reciente tras caída, uso prolongado de corticoides, dolor focal importante y deterioro funcional nuevo.',steps:[
{q:'Interpretación',o:['Cuadro rutinario sin necesidad de cambio','La combinación aumenta sospecha de fractura y justifica evaluación médica/diagnóstica','Solo aplicar masaje'],a:1,fb:'Edad, trauma y corticoides en combinación elevan la sospecha; la ruta debe escalar.'},
{q:'Conducta',o:['Continuar carga máxima','Derivar para evaluación médica oportuna y adaptar manejo según resultado','Ignorar porque no hay fiebre'],a:1,fb:'La ausencia de una bandera no neutraliza una combinación clínicamente relevante.'}]},
{id:'work',name:'Caso 3 · Retorno al trabajo',intro:'35 años, dolor lumbar recurrente. Trabajo con levantamiento repetido. Dolor moderado, alta preocupación por recaída y baja confianza. Quiere volver a jornada completa.',steps:[
{q:'Línea basal',o:['PSFS + medida de miedo/autoeficacia + demanda laboral','Solo RM','Solo fuerza manual lumbar'],a:0,fb:'La línea basal debe reflejar función específica, barreras y demanda real.'},
{q:'Progresión',o:['Ejercicio genérico sin relación laboral','Jerarquía de levantamiento, tolerancia, volumen y recuperación','Reposo hasta asintomático'],a:1,fb:'La exposición específica permite recuperar capacidad y confianza de forma verificable.'},
{q:'Alta/retorno',o:['Basarse solo en dolor 0','Combinar función, tolerancia a demanda, confianza y plan de autocuidado','Depender de terapia manual'],a:1,fb:'El retorno es una decisión funcional y contextual, no un número de dolor aislado.'}]}
];
var exam=[
{q:'Paciente con dolor lumbar persistente y RM con degeneración discal sin déficit neurológico. ¿Cuál es la interpretación más defendible?',o:['La RM demuestra la causa exacta','Los hallazgos deben contextualizarse porque son frecuentes incluso en asintomáticos','Toda degeneración requiere reposo'],a:1,r:['BRINJIKJI15']},
{q:'¿Cuál es la mejor descripción de una bandera roja?',o:['Diagnóstico automático','Dato que modifica probabilidad y puede cambiar la ruta según contexto','Síntoma que siempre exige urgencias'],a:1,r:['DOWNIE13','HAN23']},
{q:'¿Qué PROM tiene validación cultural publicada específicamente en Chile para dolor lumbar?',o:['RMDQ','TSK-11','STarT Back'],a:0,r:['GUIC14']},
{q:'STarT Back se utiliza principalmente para:',o:['Diagnosticar lesión','Estratificar riesgo pronóstico','Medir rango lumbar'],a:1,r:['HILL08']},
{q:'Según la evidencia contemporánea, el ejercicio en dolor lumbar crónico:',o:['Tiene una modalidad universalmente superior','Es una opción útil y debe individualizarse','Debe evitarse si hay dolor durante la tarea'],a:1,r:['HAYDEN21','WHO23']},
{q:'Un TSK-11 alto debe interpretarse como:',o:['Diagnóstico psiquiátrico','Señal de mayor miedo relacionado con movimiento que debe contextualizarse','Prohibición de ejercicio'],a:1,r:['GOMEZ11','ALPALHAO24']},
{q:'¿Qué combinación representa mejor cuidado centrado en la persona?',o:['Diagnóstico + técnica','Metas + preferencias + contexto + seguimiento','Imagen + reposo'],a:1,r:['WHO23']},
{q:'¿Cuál es una función razonable de terapia manual?',o:['Adjunto que puede facilitar actividad sin crear dependencia','Reposicionar estructuras de forma permanente','Reemplazar ejercicio'],a:0,r:['WHO23','GEORGE21']},
{q:'¿Qué hacer si un plan no produce el cambio esperado?',o:['Repetirlo indefinidamente','Revisar hipótesis, seguridad, dosis, barreras y adherencia','Aumentar pruebas sin pregunta'],a:1,r:['GEORGE21','WHO23']},
{q:'¿Qué define mejor el cierre de un proceso de rehabilitación?',o:['Dolor 0 obligatorio','Recuperación de participación/capacidad con plan de progresión y autocuidado','Ausencia de hallazgos en imagen'],a:1,r:['WHO23','HAYDEN21']}
];
return{refs:refs,modules:modules,scales:scales,cases:cases,exam:exam};
})();