(()=>{try{const url=new URL(window.location.href);const before=url.search;const removable=new Set(['gclid','fbclid','msclkid','mc_cid','mc_eid']);[...url.searchParams.keys()].forEach(key=>{const lower=key.toLowerCase();if(lower.startsWith('utm_')||removable.has(lower))url.searchParams.delete(key)});if(url.search!==before){history.replaceState(history.state,'',`${url.pathname}${url.search}${url.hash}`)}}catch{}})();

(()=>{
  if(document.querySelector('script[data-kc-runtime]'))return;
  const runtime=document.createElement('script');runtime.src='../assets/runtime-config.js?v=20260807-1';runtime.async=false;runtime.dataset.kcRuntime='true';
  runtime.addEventListener('load',()=>{if(document.querySelector('script[data-kc-observability]'))return;const obs=document.createElement('script');obs.src='../assets/observability.js?v=20260807-1';obs.async=false;obs.dataset.kcObservability='true';document.head.appendChild(obs);});document.head.appendChild(runtime);
})();

document.addEventListener('DOMContentLoaded',()=>{
  const style=document.createElement('style');
  style.textContent='.recommendation-badge{display:inline-flex;align-self:flex-start;margin:0 0 .85rem;padding:.38rem .7rem;border-radius:999px;background:var(--green);color:#05241b;font-size:.72rem;font-weight:950;letter-spacing:.06em;text-transform:uppercase}.recommendation-badge[hidden]{display:none}.product.recommended{border-color:rgba(85,214,165,.8);box-shadow:0 0 0 2px rgba(85,214,165,.16),0 24px 60px rgba(0,0,0,.28);transform:translateY(-5px)}.purchase-trust{margin:.55rem 0 0!important;padding:.7rem .8rem;border-radius:.75rem;background:rgba(255,255,255,.04);font-size:.78rem!important;line-height:1.4;color:#c8dadd!important;text-align:center}.kc-privacy-notice{margin:1.25rem auto;padding:1rem 1.1rem;max-width:1100px;border:1px solid rgba(114,231,223,.35);border-radius:14px;background:rgba(7,34,40,.92);color:#eafafa;line-height:1.55}.kc-privacy-notice strong{color:#8ef1e7}.product{transition:.25s transform,.25s border-color,.25s box-shadow}.product:focus{outline:3px solid rgba(85,214,165,.42);outline-offset:4px}.kc-testimonials{position:relative;overflow:hidden;background:linear-gradient(180deg,#06191f,#08262c);color:#f4fbfb}.kc-testimonials::before{content:"";position:absolute;inset:-12rem -10rem auto auto;width:30rem;height:30rem;border-radius:50%;background:radial-gradient(circle,rgba(75,218,205,.12),transparent 68%);pointer-events:none}.kc-testimonials .section-head{position:relative;z-index:1;max-width:850px}.kc-testimonials .section-head p{color:#a9c3ca}.kc-testimonial-grid{position:relative;z-index:1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-top:1.6rem}.kc-testimonial{display:flex;flex-direction:column;min-width:0;padding:1.3rem;border:1px solid rgba(114,231,223,.16);border-radius:18px;background:rgba(3,24,30,.66);box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 18px 44px rgba(0,0,0,.12)}.kc-testimonial .quote-mark{display:block;margin-bottom:.55rem;color:#72e7df;font-size:1.8rem;font-weight:900;line-height:1}.kc-testimonial blockquote{margin:0;color:#d7e7e9;font-size:.92rem;line-height:1.62}.kc-testimonial footer{display:block;margin-top:auto;padding-top:1rem;border-top:1px solid rgba(255,255,255,.07);background:none;color:inherit}.kc-testimonial footer strong{display:block;color:#fff;font-size:.86rem}.kc-testimonial footer span{display:block;margin-top:.18rem;color:#83a5ab;font-size:.72rem}.kc-testimonial-privacy{position:relative;z-index:1;margin:1rem 0 0;color:#7f9ea4;font-size:.72rem;line-height:1.5}.kc-testimonial-privacy strong{color:#9bc2c6}@media(max-width:900px){.kc-testimonial-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.product.recommended{transform:none}.kc-testimonial-grid{grid-template-columns:1fr}.kc-testimonial{padding:1.15rem}}';document.head.appendChild(style);

  const path=location.pathname;
  const educational=path.includes('/estudiantes')||path.includes('/profesionales');
  if(educational){const main=document.querySelector('main');if(main&&!document.querySelector('.kc-privacy-notice')){const n=document.createElement('div');n.className='kc-privacy-notice';n.innerHTML='<strong>Uso educativo y formativo.</strong> KineCheck Clínico y KineCheck Estudiante no son fichas clínicas ni repositorios de pacientes. En ejercicios, casos, notas o campos de práctica utiliza exclusivamente información ficticia, simulada o debidamente anonimizada. No ingreses nombres, RUT, teléfonos, correos, fotografías identificables, números de ficha ni otros datos que permitan identificar a un paciente real.';main.insertBefore(n,main.children[1]||null);}}

  document.querySelectorAll('a[href*="kinecheck-recupera"],a[href="./recupera/"],a[href="../recupera/"]').forEach(a=>{a.removeAttribute('target');a.href='/recupera/';const text=(a.textContent||'').trim();if(text&&!text.toLowerCase().includes('próximamente'))a.textContent=text+' · Próximamente';});
  document.querySelectorAll('.audience-card.rec').forEach(card=>{const p=card.querySelector('p');if(p)p.textContent='KineCheck Recupera está en revisión de privacidad y protección de datos antes de su habilitación.';const b=card.querySelector('b');if(b)b.textContent='Próximamente →';});

  const isHome=path==='/'||path.endsWith('/index.html');
  if(isHome&&!document.querySelector('.kc-testimonials')){
    const main=document.querySelector('main');
    const howItWorks=[...main?.querySelectorAll('section.section')||[]].find(section=>section.querySelector('.section-head .eyebrow')?.textContent.trim()==='CÓMO FUNCIONA');
    if(main&&howItWorks){
      const testimonials=document.createElement('section');
      testimonials.className='section kc-testimonials';
      testimonials.setAttribute('aria-labelledby','kc-testimonials-title');
      testimonials.innerHTML=`
        <div class="section-head">
          <span class="eyebrow">EXPERIENCIAS BETA</span>
          <h2 id="kc-testimonials-title">Lo que dijeron quienes probaron KineCheck.</h2>
          <p>Comentarios reales recibidos durante la etapa beta. Para proteger la privacidad, se muestran solo nombres parciales y una referencia general a su participación.</p>
        </div>
        <div class="kc-testimonial-grid">
          <article class="kc-testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>Me pareció una herramienta sumamente interesante y de gran valor. La información es clara, comprensible y muy bien respaldada con evidencia científica. La interfaz me pareció amigable e intuitiva.</blockquote><footer><strong>Manuel A.</strong><span>Tester beta · profesional de la salud</span></footer></article>
          <article class="kc-testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>La sección de evidencia científica me pareció muy útil porque ayuda a pensar mejor, redactar y darle otra visión a las situaciones. Los botones y la información son excelentes y todo queda claro desde el primer minuto. Me encantó.</blockquote><footer><strong>Pascale A.</strong><span>Tester beta · estudiante</span></footer></article>
          <article class="kc-testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>Leí y apreté cuanto pude. No me salieron fallas y los enlaces que probé se abrieron correctamente y me dirigieron a las fuentes. La única falla fue la del comienzo y la solucionaron de inmediato. Me encantó el curso. Recomendado.</blockquote><footer><strong>Moisés A.</strong><span>Tester beta</span></footer></article>
          <article class="kc-testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>Buenísima aplicación, buenísima plataforma. Cursos totalmente recomendados para profesionales del área de la salud.</blockquote><footer><strong>Cristopher</strong><span>Tester beta · profesional de la salud</span></footer></article>
          <article class="kc-testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>Totalmente recomendado. Muy buen sustento y actualización. Lo haría mil veces más.</blockquote><footer><strong>Natalia</strong><span>Tester beta · profesional de la salud</span></footer></article>
          <article class="kc-testimonial"><span class="quote-mark" aria-hidden="true">“</span><blockquote>Buenísimo. Espero nuevos cursos. Totalmente recomendado.</blockquote><footer><strong>Daniela</strong><span>Tester beta · profesional de la salud</span></footer></article>
        </div>
        <p class="kc-testimonial-privacy"><strong>Privacidad:</strong> no se publican apellidos completos, correos electrónicos, instituciones ni otros datos de identificación o contacto.</p>`;
      main.insertBefore(testimonials,howItWorks);
    }
  }

  const button=document.querySelector('[data-menu-button]'),nav=document.querySelector('[data-public-nav]');if(button&&nav){button.addEventListener('click',()=>{const open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Abrir menú');}));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav.classList.contains('open')){nav.classList.remove('open');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Abrir menú');button.focus();}});}
  document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href');if(id&&id.length>1){const target=document.querySelector(id);if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth',block:'start'});}}}));
  const support=document.querySelectorAll('[data-support-email]');if(support.length){const address='soporte.kinecheck@gmail.com';support.forEach(link=>{link.href=`mailto:${address}`;link.textContent=address;});}
  const products=[...document.querySelectorAll('.product-showcase .product')];products.forEach((card,index)=>{card.dataset.profile=['pro','est','rec'][index]||'';const badge=document.createElement('span');badge.className='recommendation-badge';badge.textContent='Recomendado para comenzar';badge.hidden=index!==0;card.insertBefore(badge,card.querySelector('.product-preview'));const trust=document.createElement('p');trust.className='purchase-trust';trust.textContent='Compra procesada por Hotmart. Revisa las condiciones de pago y reembolso antes de finalizar.';const actions=card.querySelector('.product-actions');if(actions)actions.appendChild(trust);});
});
