const L=(id,title,focus,core,guideFields,actions,pitfalls,decisions,caseText,task,evidence,question,options,answer,rationale)=>({id,title,focus,core,guideFields,actions,pitfalls,decisions,case:caseText,task,evidence,quiz:{question,options,answer,rationale}});
const M=(id,title,purpose,objectives,lessons)=>({id,title,purpose,objectives,lessons});

window.__KINECHECK_COURSE_PAYLOAD__={
  title:"KineCheck Clínico",
  subtitle:"Curso avanzado para profesionales sobre evaluación, seguridad y razonamiento musculoesquelético. La guía digital complementaria permite aplicar el método sin reemplazar la ficha clínica institucional.",
  version:"2026.08.06-profesional-1",
  audience:"Kinesiólogos y profesionales de rehabilitación musculoesquelética",
  durationHours:18,
  caseCount:30,
  modules:[
    M("m1","La guía complementaria y el estándar profesional","Delimitar qué problema resuelve KineCheck Clínico, qué no debe hacer y cómo integrarlo sin competir con la ficha clínica institucional.",[
      "Diferenciar guía de razonamiento, registro clínico oficial y herramienta de apoyo.",
      "Aplicar minimización de datos y anonimización en todo ejercicio.",
      "Definir un flujo de uso antes, durante y después de la atención."
    ],[
      L("m1-l1","El curso es el centro; la guía es el adjunto","Propósito, alcance y límites","KineCheck Clínico enseña a evaluar y decidir. La guía digital ayuda a no omitir dominios relevantes y a ordenar el razonamiento; no acredita una atención, no reemplaza la ficha institucional y no convierte casillas completas en juicio clínico.",["motivo de consulta","resumen del caso","hipótesis","próximos pasos"],["Usar la guía como lista de verificación flexible, no como interrogatorio lineal.","Documentar en la ficha oficial lo exigido por la institución.","Trabajar en el curso con casos ficticios o anonimizados."],["Copiar información identificable de una persona real.","Creer que completar todos los campos equivale a una buena evaluación.","Usar la guía para justificar decisiones no razonadas."],["Qué información es imprescindible para la decisión actual.","Qué pertenece al registro oficial.","Cuándo abandonar la guía y priorizar una necesidad emergente."],"Una clínica ya dispone de ficha electrónica obligatoria. El kinesiólogo quiere usar KineCheck para revisar su razonamiento antes de cerrar la sesión.","Diseña un flujo de tres minutos que use la guía sin duplicar el registro ni ingresar datos identificables.","Las recomendaciones transversales de buena práctica priorizan atención centrada en la persona, examen físico, evaluación psicosocial, vigilancia de evolución y decisiones individualizadas.","¿Cuál es el uso más defendible de la guía digital?",["Reemplazar la ficha institucional cuando sea más cómoda.","Almacenar todos los antecedentes para construir una base clínica.","Apoyar la revisión del razonamiento y luego documentar en el sistema oficial.","Producir un diagnóstico automático a partir de campos completos."],2,"La guía es apoyo complementario; la documentación oficial, la protección de datos y el juicio profesional permanecen fuera de ella."),
      L("m1-l2","Datos mínimos, anonimización y trazabilidad","Ética operativa","En una herramienta educativa complementaria, el estándar prudente es no ingresar nombres, RUT, direcciones, teléfonos, fotografías identificables ni narrativas que permitan reconocer a la persona.",["identificador ficticio","contexto","observaciones","exportación"],["Usar códigos no reversibles y casos simulados.","Separar apuntes educativos del registro asistencial.","Eliminar notas temporales cuando dejan de ser necesarias."],["Creer que omitir el nombre siempre anonimiza.","Compartir capturas con datos indirectos.","Exportar a dispositivos o correos no autorizados."],["Si un dato cambia realmente la decisión.","Si existe un sistema autorizado para tratarlo.","Cómo responder ante una brecha o error."],"Un profesional desea fotografiar una pantalla de la guía para discutir el caso con colegas.","Identifica cinco elementos que podrían reidentificar al paciente aunque su nombre no aparezca.","La minimización de datos reduce exposición innecesaria. El diseño educativo debe privilegiar ejemplos ficticios y resúmenes no identificables.","¿Qué práctica reduce mejor el riesgo de reidentificación?",["Reemplazar el nombre por iniciales.","Usar un caso simulado sin fechas, lugares ni rasgos únicos.","Guardar la captura en el teléfono personal.","Enviar la ficha por mensajería privada."],1,"Un caso simulado evita el tratamiento innecesario de datos reales y elimina identificadores directos e indirectos."),
      L("m1-l3","De la casilla a la decisión clínica","Razonamiento explícito","Un dato adquiere valor cuando modifica una hipótesis, una decisión de seguridad, una medición o el plan de reevaluación. El profesional debe explicar por qué preguntó, qué cambió y qué incertidumbre permanece.",["hallazgo","interpretación","alternativa","reevaluación"],["Separar observación, inferencia y decisión.","Mantener una hipótesis alternativa.","Definir qué dato futuro cambiaría el plan."],["Confundir hallazgo con causa.","Cerrar por familiaridad.","Acumular pruebas sin impacto decisional."],["Qué hipótesis aumenta o disminuye.","Qué acción es proporcional al riesgo.","Qué resultado indicará continuar o cambiar."],"Una prueba especial resulta positiva, pero la historia y el patrón funcional no son coherentes con la etiqueta sugerida.","Redacta tres frases: dato observado, interpretación probabilística y decisión provisional.","La educación del razonamiento mejora cuando explicita recolección de datos, hipótesis, justificación, decisión y feedback en casos activos.","¿Qué formulación refleja mejor razonamiento clínico?",["La prueba positiva confirma la lesión.","El hallazgo aumenta la plausibilidad, pero debe integrarse con historia y alternativas.","La estructura dolorosa es la causa.","Se requieren todas las pruebas antes de decidir."],1,"El lenguaje probabilístico evita sobreinterpretar un hallazgo aislado." )
    ]),
    M("m2","Seguridad, triage y detección de patología relevante","Priorizar condiciones que requieren derivación, precaución o modificación antes de profundizar en el diagnóstico musculoesquelético.",[
      "Construir hipótesis de seguridad desde la historia.","Interpretar banderas rojas como señales contextuales, no diagnósticos.","Definir conducta, urgencia y comunicación ante riesgo."
    ],[
      L("m2-l1","Banderas rojas: señales, combinaciones y contexto","Riesgo clínico","Una bandera roja aislada suele tener capacidad diagnóstica limitada. Su valor aumenta al combinarse con prevalencia, evolución, antecedentes, signos sistémicos y hallazgos del examen.",["banderas rojas","antecedentes","síntomas sistémicos","conducta"],["Preguntar por trauma, cáncer, infección, pérdida de peso, inmunosupresión y síntomas neurológicos.","Valorar conjuntos coherentes.","Documentar la conducta derivada."],["Derivar por toda señal inespecífica.","Descartar riesgo por una prueba negativa.","Usar listas idénticas para toda región."],["Urgencia de derivación.","Necesidad de evaluación médica o imagen.","Qué intervención evitar mientras se aclara."],"Dolor lumbar reciente en persona de 72 años, uso prolongado de corticoides y dolor tras caída menor.","Construye una representación del problema y define la conducta inicial.","La revisión de guías de 2025 muestra variación en definiciones y refuerza una interpretación estandarizada, contextual y orientada a conducta.","¿Qué principio es más seguro?",["Toda bandera roja obliga a urgencias.","Una bandera roja nunca es útil.","Las señales deben integrarse y vincularse a una conducta proporcional.","Una prueba física negativa elimina patología grave."],2,"La utilidad está en combinar señales, estimar riesgo y decidir una acción proporcionada."),
      L("m2-l2","Cribado neurológico y deterioro progresivo","Déficit y urgencia","La evaluación neurológica busca patrones, severidad, simetría, progresión y concordancia. La urgencia depende de la trayectoria y del impacto funcional, no solo de que exista un síntoma.",["miotomas","dermatomas","reflejos","fuerza","sensibilidad","esfínteres"],["Comparar lados y niveles relevantes.","Registrar cambios objetivos.","Priorizar progresión motora y alteraciones esfinterianas."],["Llamar radiculopatía a toda irradiación.","Confiar en una maniobra neurodinámica.","No registrar línea basal."],["Derivación inmediata o preferente.","Qué hallazgo monitorizar.","Qué carga es prudente."],"Dolor cervical con parestesias intermitentes que evoluciona a pérdida de destreza y debilidad progresiva de la mano.","Ordena preguntas y pruebas que distingan irritación neural, radiculopatía y compromiso medular.","La exactitud de pruebas físicas para radiculopatía cervical es variable y de certeza muy baja; su utilidad aumenta dentro de un conjunto clínico.","¿Qué hallazgo cambia más la prioridad?",["Dolor 7/10 sin cambio funcional.","Parestesia ocasional estable.","Debilidad motora objetivable y progresiva.","Spurling positivo aislado."],2,"La progresión de déficit motor objetivo exige una conducta más urgente."),
      L("m2-l3","Región cervical y posible patología vascular","Marco IFOMPT","La seguridad cervical se construye desde historia, factores de riesgo, presentación y examen dirigido. Las pruebas posicionales aisladas no autorizan intervenciones cervicales.",["cefalea","mareo","síntomas craneales","factores vasculares","presión arterial","pares craneales"],["Buscar inicio súbito y síntomas atípicos.","Usar el marco IFOMPT para organizar hipótesis.","Posponer intervenciones ante incertidumbre relevante."],["Usar una prueba provocativa como autorización.","Reducir todo mareo a causa cervical.","Ignorar cambios cualitativos."],["Compatibilidad con atención MSK.","Examen adicional necesario.","Cuándo derivar y cómo comunicar."],"Dolor cervical nuevo, cefalea intensa distinta, náuseas y alteración transitoria del habla.","Explica por qué la prioridad no es medir movilidad.","El marco IFOMPT orienta el razonamiento ante posibles patologías vasculares antes de intervenciones cervicales.","¿Qué conducta es más defendible?",["Medir movilidad para confirmar origen mecánico.","Hacer una prueba posicional y continuar si es negativa.","Interrumpir el examen rutinario y gestionar derivación urgente.","Tratar suavemente y reevaluar."],2,"La combinación de síntomas atípicos y neurológicos exige priorizar una posible patología vascular." )
    ]),
    M("m3","Historia clínica, comportamiento de síntomas e irritabilidad","Transformar la anamnesis en una representación útil del problema, sin rigidizarla en una secuencia de preguntas.",[
      "Caracterizar síntomas, función y trayectoria.","Utilizar irritabilidad para graduar el examen.","Distinguir patrones mecánicos, sistémicos y neuropáticos."
    ],[
      L("m3-l1","ALICIA y cronología con propósito","Anamnesis estructurada","Localización, inicio, características, intensidad, agravantes y atenuantes sirven cuando generan hipótesis. La cronología debe explicar cómo empezó, qué cambió y qué eventos modificaron el cuadro.",["localización","inicio","carácter","intensidad","agravantes","atenuantes","evolución"],["Comenzar con narración abierta.","Relacionar síntomas con actividad y participación.","Distinguir síntoma principal y asociados."],["Interrumpir pronto.","Hacer de la intensidad el único resultado.","No preguntar qué significa el problema."],["Qué patrón explorar.","Qué actividad será referencia.","Qué hipótesis no encaja."],"Dolor de hombro de seis meses al vestirse; la preocupación principal es no poder cargar a un nieto.","Construye una representación de una frase que integre tiempo, función y preocupación.","La atención centrada en la persona y la evaluación biopsicosocial son recomendaciones consistentes en guías de alta calidad.","¿Qué pregunta aporta más?",["¿Cuánto duele?","¿Qué movimiento duele?","¿Qué actividad importante dejó de hacer y qué teme?","¿Tuvo el mismo diagnóstico antes?"],2,"Vincula síntomas, función, significado y expectativas."),
      L("m3-l2","SINS e irritabilidad como marco, no puntaje","Severidad e irritabilidad","La irritabilidad integra magnitud de provocación, tiempo hasta aparecer, recuperación y estabilidad. Orienta cuánto y con qué intensidad examinar, pero no es una escala diagnóstica validada universal.",["severidad","irritabilidad","naturaleza","etapa","estabilidad","respuesta 24 horas"],["Definir una prueba comparable segura.","Dosificar según facilidad de provocación y recuperación.","Observar respuesta diferida."],["Etiquetar sin criterios.","Provocar repetidamente.","Confundir dolor alto con irritabilidad alta."],["Extensión del examen.","Orden de pruebas.","Qué respuesta obliga a reducir carga."],"Dolor de rodilla 8/10 que cesa al terminar versus 4/10 que aumenta durante horas tras sentadilla.","Compara severidad e irritabilidad y decide cómo examinar.","Los marcos descriptivos pueden estructurar decisiones, pero no deben presentarse como instrumentos validados si no lo son.","¿Qué describe mejor alta irritabilidad?",["Dolor intenso que cesa de inmediato.","Síntomas fáciles de provocar y lentos de recuperar.","Cualquier dolor mayor a 7/10.","Miedo elevado."],1,"La irritabilidad depende del umbral de provocación y de la recuperación."),
      L("m3-l3","Patrones de dolor y mecanismos como hipótesis","Nociceptivo, neuropático y nociplástico","Los descriptores de mecanismos organizan hipótesis, pero rara vez son categorías puras. Deben apoyarse en distribución, temporalidad, signos neurológicos, hipersensibilidad y contexto.",["distribución","calidad","neuroanatomía","hipersensibilidad","sueño","fatiga"],["Buscar coherencia neuroanatómica.","Considerar mecanismos mixtos.","Usar criterios nociplásticos con prudencia."],["Llamar neuropático a todo dolor quemante.","Explicar dolor persistente como solo cerebral.","Convertir cuestionarios en diagnóstico."],["Qué examen discrimina hipótesis.","Cómo comunicar incertidumbre.","Qué seguir longitudinalmente."],"Dolor multirregional de cuatro años, sueño no reparador, sensibilidad aumentada y hormigueo sin patrón estable.","Formula un perfil de mecanismos mixtos y define qué no puede concluirse.","Los criterios IASP de dolor nociplástico requieren duración, distribución, insuficiencia de explicaciones nociceptiva o neuropática y signos de hipersensibilidad.","¿Cuál es la interpretación más prudente?",["La hipersensibilidad confirma sensibilización central.","Es psicológico porque no sigue dermatoma.","Puede existir componente nociplástico, manteniendo alternativas y contexto.","El dolor persistente deja de ser nociceptivo."],2,"Los mecanismos pueden coexistir y la clasificación no explica toda la causalidad." )
    ]),
    M("m4","Persona, contexto y factores psicosociales","Integrar valores, expectativas, salud mental, sueño, trabajo y participación sin reducir la experiencia a etiquetas.",[
      "Explorar factores psicosociales sin estigma.","Diferenciar riesgo, barrera y diagnóstico de salud mental.","Construir decisiones compartidas y metas significativas."
    ],[
      L("m4-l1","Banderas amarillas y naranjas sin etiquetar","Factores modificadores","Miedo, catastrofismo, baja autoeficacia, estrés o ánimo pueden modificar pronóstico y conducta. Sirven para adaptar atención, no para atribuir el dolor a la mente.",["creencias","miedo","ánimo","estrés","autoeficacia","apoyo"],["Preguntar con permiso.","Relacionar factores con conducta o meta.","Derivar cuando excede competencia o existe riesgo."],["Usar bandera amarilla como etiqueta.","Interpretar puntaje como diagnóstico psiquiátrico.","Contraponer físico y psicológico."],["Qué factor es prioritario.","Qué requiere trabajo interdisciplinario.","Cómo adaptar lenguaje y carga."],"Persona evita agacharse porque cree que el disco puede salirse.","Redacta una respuesta que valide, explore y proponga un experimento seguro.","Las guías de dolor MSK recomiendan evaluar factores psicosociales y mantener atención centrada en la persona.","¿Qué respuesta es más útil?",["Está solo en su cabeza.","Su miedo retrasa la recuperación.","Tiene sentido que proteja su espalda; revisemos qué teme y probemos una forma segura.","La resonancia dirá si puede moverse."],2,"Valida sin confirmar la amenaza y abre una prueba colaborativa."),
      L("m4-l2","Sueño, carga, trabajo y vida cotidiana","Determinantes funcionales","Sueño, carga laboral, cuidado de otros, recursos y participación pueden ser tan decisivos como un hallazgo físico. Deben convertirse en variables observables.",["sueño","trabajo","actividad física","carga","participación","recursos"],["Identificar ciclos entre síntomas, sueño y actividad.","Distinguir demanda, control y apoyo laboral.","Seleccionar cambios viables."],["Prescribir cambios imposibles.","Culpar estilos de vida.","Registrar factores sin vincularlos al plan."],["Qué barrera modificar primero.","Cómo ajustar al contexto.","Qué indicador mostrará cambio."],"Trabajadora nocturna y cuidadora principal con dolor cervical y poco tiempo.","Diseña una intervención mínima viable y una medida de seguimiento.","La OMS destaca evaluación integral, actividad, sueño, bienestar y participación como componentes de rehabilitación.","¿Qué plan es más centrado?",["45 minutos diarios estándar.","Reposo hasta normalizar sueño.","Opción breve acordada, vinculada a una actividad y revisada según respuesta.","Derivación por baja adherencia."],2,"La viabilidad y la decisión compartida forman parte de la calidad."),
      L("m4-l3","Metas y decisiones compartidas","Participación activa","La decisión compartida exige confianza, comunicación bidireccional, comparación de opciones y poder real para elegir. Una meta debe conectar con actividad o participación valorada.",["expectativas","preferencias","metas","opciones","acuerdo"],["Preguntar cuánto desea participar.","Explicar opciones, límites y cargas.","Formular metas revisables."],["Presentar una única opción.","Reducir la meta a dolor.","Confundir consentimiento con colaboración."],["Qué resultado importa.","Qué trade-offs acepta.","Cuándo revisar la decisión."],"Se comparan terapia presencial frecuente y programa autónomo con controles espaciados.","Conduce una conversación que permita elegir sin presionar.","La síntesis cualitativa en fisioterapia MSK identifica confianza, comunicación, preferencias y capacidad para decidir como condiciones centrales.","¿Qué distingue la decisión compartida?",["Firmar consentimiento.","El profesional explica su recomendación.","Las preferencias pueden cambiar realmente la elección.","La persona obedece porque confía."],2,"La participación debe tener capacidad real de modificar la decisión." )
    ]),
    M("m5","Examen físico orientado por hipótesis","Seleccionar observación, movimiento, palpación y pruebas según seguridad, irritabilidad y utilidad decisional.",[
      "Diseñar un examen mínimo suficiente.","Diferenciar movimiento activo, pasivo y resistido.","Evitar acumulación indiscriminada de pruebas."
    ],[
      L("m5-l1","Observación y movimiento funcional","Entrada al examen","La observación útil describe estrategia, tolerancia, confianza y relación con la tarea. No debe transformarse en juicios posturales causales sin evidencia.",["inspección","marcha","tarea funcional","estrategia","confianza"],["Observar una tarea relevante.","Describir sin inferir causa.","Repetir tras una modificación."],["Diagnosticar por postura.","Corregir toda asimetría.","Confundir variación con disfunción."],["Qué tarea representa el problema.","Qué modificación explorar.","Qué medida repetir."],"Corredor con dolor de rodilla y valgo dinámico en sentadilla unipodal.","Distingue descripción, hipótesis y decisión sin afirmar causalidad.","La buena práctica recomienda examen físico y monitorización; los hallazgos se integran con función y contexto.","¿Cuál frase es más rigurosa?",["El valgo causa el dolor.","Se observa aducción y rotación; exploraremos si modificarla cambia síntomas o rendimiento.","La mala técnica confirma debilidad glútea.","Toda asimetría requiere corrección."],1,"Describe y propone un experimento sin convertir el hallazgo en causa."),
      L("m5-l2","Movimiento activo, pasivo y resistido","Tejidos, función y respuesta","Comparar movimiento activo, pasivo y resistido organiza hipótesis sobre capacidad contráctil, movilidad, dolor y control, pero no identifica por sí solo una estructura responsable.",["ROM activo","ROM pasivo","movimiento resistido","fin de rango","respuesta"],["Definir posición y criterio de detención.","Registrar dolor, rango y calidad.","Comparar con línea basal pertinente."],["Usar patrones capsulares como diagnóstico automático.","Forzar fin de rango.","Ignorar variabilidad."],["Qué componente limita función.","Qué merece cuantificación.","Qué prueba discrimina."],"Hombro con elevación activa limitada, pasiva casi completa y debilidad dolorosa.","Genera tres hipótesis y selecciona la siguiente prueba útil.","Los patrones actualizan probabilidades; requieren historia, precisión de medición y alternativas.","¿Qué conclusión es defendible?",["Existe rotura.","El patrón orienta a explorar capacidad contráctil, control y dolor sin confirmar lesión.","La pasiva normal descarta patología grave.","La debilidad identifica el tendón."],1,"El patrón orienta el examen, no demuestra estructura o causa."),
      L("m5-l3","Palpación y movimientos accesorios","Información con límites","La palpación localiza sensibilidad, temperatura, edema o respuesta; los movimientos accesorios exploran movilidad y síntomas. La especificidad de interpretaciones segmentarias suele ser limitada.",["palpación","edema","temperatura","movilidad accesoria","respuesta"],["Definir qué se observa o reproduce.","Usar la respuesta como hipótesis o prueba de intervención.","Evitar narrativas de recolocación."],["Afirmar desalineación.","Confundir reproducción con causa.","Tratar hallazgos sin impacto funcional."],["Si cambia seguridad o plan.","Si sirve como adjunto.","Cómo reevaluar sin mecanismo inventado."],"Palpación lumbar reproduce dolor y movilización lo reduce temporalmente.","Explica el hallazgo sin hablar de vértebras fuera de lugar.","La terapia manual se recomienda como adjunto y debe integrarse con estrategias activas y reevaluación.","¿Qué explicación evita sobreafirmar?",["Encontramos la vértebra bloqueada.","La palpación identificó la causa.","La zona es sensible y el alivio temporal puede facilitar función; reevaluaremos.","La respuesta confirma mecanismo articular."],2,"Describe observación y utilidad sin atribuir causa estructural no demostrada." )
    ]),
    M("m6","Medición: movilidad, fuerza y desempeño","Obtener medidas comparables, interpretar error y elegir instrumentos que cambien decisiones.",[
      "Estandarizar goniometría y dinamometría.","Distinguir cambio real de variación.","Seleccionar desempeño vinculado a metas."
    ],[
      L("m6-l1","Goniometría y rango de movimiento","Protocolos reproducibles","Una medida útil requiere posición, referencias, instrumento, intentos, dolor y condiciones comparables. Un número sin protocolo no es trazable.",["goniometría","posición","referencias","intentos","dolor","lado"],["Usar el mismo protocolo.","Registrar condiciones relevantes.","Interpretar junto con error y función."],["Precisión falsa.","Comparar protocolos distintos.","Confundir diferencia con relevancia."],["Si el rango es objetivo relevante.","Qué magnitud cambia el plan.","Si es estable para seguimiento."],"Flexión de rodilla cambia 118° a 123° con distinta posición pélvica.","Decide si puedes afirmar mejora y qué información falta.","Toda medida exige fiabilidad, error estándar, cambio detectable y consistencia del protocolo.","¿Qué aumenta más la interpretabilidad?",["Un decimal adicional.","Misma posición, referencias y condiciones.","Valores normativos genéricos.","Una sola medición."],1,"La estandarización permite comparación longitudinal."),
      L("m6-l2","Fuerza: MMT, Oxford y dinamometría","Capacidad contráctil","El test manual sirve para déficits grandes y cribado, pero tiene techo. La dinamometría cuantifica si protocolo, estabilización y fuerza del examinador son adecuados.",["MMT/Oxford","dinamometría","posición","estabilización","normalización"],["Elegir instrumento según pregunta.","Estandarizar palanca y fijación.","Reportar unidades."],["Usar 5/5 para descartar déficit.","Comparar palancas distintas.","Ignorar dolor y aprendizaje."],["Qué detectará el cambio esperado.","Si limita dolor o capacidad.","Qué asimetría importa."],"Deportista con 5/5 bilateral en extensión de rodilla y diferencia marcada en salto.","Explica por qué MMT es insuficiente y diseña medición objetiva.","Revisiones 2023-2026 muestran buena fiabilidad de dinamometría portátil en varios protocolos, con dependencia de posición y fijación.","¿Cuándo es especialmente útil la dinamometría?",["Para presencia de contracción.","Para diferencias sutiles o seguimiento cuantitativo.","Sin estabilización posible.","Para confirmar diagnóstico anatómico."],1,"La cuantificación mejora sensibilidad para diferencias y cambios con protocolo fiable."),
      L("m6-l3","Pruebas de desempeño y capacidad funcional","Medir lo que importa","Las pruebas de desempeño conectan capacidad corporal con actividades. Deben elegirse por seguridad, pertinencia, reproducibilidad y sensibilidad al cambio.",["sit-to-stand","salto","equilibrio","marcha","capacidad","síntomas"],["Relacionar prueba con meta.","Definir calidad y detención.","Registrar rendimiento, síntomas y confianza."],["Prueba demasiado exigente.","Medir solo tiempo.","Fatigar sin propósito."],["Qué representa la demanda.","Qué limita rendimiento.","Qué cambio permite progresar."],"Persona desea subir escaleras y levantarse del suelo, pero se evalúa solo fuerza isométrica.","Selecciona dos pruebas de desempeño.","Los conjuntos de resultados incluyen dolor, función específica, desempeño, participación y metas.","¿Qué criterio domina la selección?",["Muchos valores normativos.","Que sea fácil de grabar.","Que represente una demanda relevante y repetible con seguridad.","Que produzca fatiga máxima."],2,"La utilidad depende de pertinencia, seguridad y capacidad para informar decisiones." )
    ]),
    M("m7","Examen neurológico y neurodinámica","Evaluar función neural y mecanosensibilidad sin convertir pruebas provocativas en diagnósticos.",[
      "Organizar un cribado neurológico regional.","Interpretar neurodinámica con diferenciación.","Reconocer patrones centrales, periféricos y discordantes."
    ],[
      L("m7-l1","Miotomas, dermatomas y reflejos","Patrones neurológicos","Los hallazgos neurológicos se analizan como patrones convergentes y se comparan longitudinalmente. La variabilidad anatómica limita interpretaciones rígidas.",["fuerza segmentaria","sensibilidad","reflejos","simetría","progresión"],["Usar varios dominios.","Registrar distribución y severidad.","Repetir si hay progresión."],["Asignar raíz por un músculo.","No tener línea basal.","Ignorar signos centrales."],["Localización y alternativas.","Prioridad de derivación.","Qué monitorizar."],"Debilidad de extensión de muñeca, reflejo disminuido y parestesia radial con dolor cervical.","Integra los hallazgos y define qué falta.","La concordancia entre historia y varios hallazgos es más útil que una señal aislada.","¿Qué aumenta la confianza radicular?",["Dermatoma doloroso aislado.","Conjunto concordante motor, sensitivo, reflejo e historia.","Resonancia degenerativa.","ULNT positivo aislado."],1,"La convergencia compatible es más informativa."),
      L("m7-l2","Neurodinámica y diferenciación estructural","Mecanosensibilidad neural","Una prueba positiva requiere reproducción relevante, comparación y cambio con diferenciación estructural. La tensión normal no equivale a patología.",["ULNT","SLR","slump","síntoma familiar","diferenciación"],["Comparar respuesta.","Usar diferenciación.","Integrar con examen neurológico."],["Definir positividad solo por rango.","Provocar intensamente.","Diagnosticar atrapamiento por una prueba."],["Si hay mecanosensibilidad relevante.","Qué dosis tolera.","Qué alternativa explica respuesta."],"ULNT1 reproduce tirantez bilateral, pero solo el lado sintomático cambia con inclinación cervical y reproduce parestesia habitual.","Explica qué aporta la diferenciación y qué no confirma.","La revisión 2026 de radiculopatía cervical encontró certeza muy baja y exactitud variable; las combinaciones ayudan, no sustituyen el conjunto clínico.","¿Qué hace más interpretable la prueba?",["Menor rango.","Cualquier tensión.","Síntoma relevante modificado con diferenciación.","Dolor intenso."],2,"La relevancia y diferenciación apoyan mecanosensibilidad."),
      L("m7-l3","Patrones centrales y periféricos","Diferencial neurológico","Alteraciones bilaterales, marcha, destreza, hiperreflexia o signos patológicos amplían el diferencial más allá de raíz o nervio periférico.",["marcha","destreza","tono","signos patológicos","distribución bilateral"],["Observar marcha y tareas finas.","Explorar neurona motora superior.","Priorizar progresión y combinaciones."],["Atribuir todo al dolor.","No examinar miembros inferiores.","Esperar presentación completa."],["Posible compromiso central.","Derivación prioritaria.","Qué intervención evitar."],"Dolor cervical con torpeza de manos, marcha insegura y sensación eléctrica al flexionar cuello.","Formula diferencial y conducta.","Los marcos de seguridad cervical promueven hipótesis amplias y priorización ante signos no compatibles con un problema periférico simple.","¿Qué combinación preocupa por compromiso central?",["Dolor local y rigidez.","Parestesia unilateral estable.","Torpeza bilateral, alteración de marcha e hiperreflexia.","Dolor que mejora con calor."],2,"La combinación de signos centrales requiere evaluación prioritaria." )
    ]),
    M("m8","Pruebas especiales, clusters y razonamiento probabilístico","Interpretar exactitud diagnóstica sin sobrevalorar etiquetas anatómicas.",[
      "Seleccionar pruebas según probabilidad previa.","Usar clusters solo cuando sean aplicables.","Comunicar resultados probabilísticamente."
    ],[
      L("m8-l1","Probabilidad pretest y utilidad de una prueba","Antes de probar","Una prueba solo es útil si existe una hipótesis plausible y su resultado puede cambiar una decisión. La probabilidad previa proviene de prevalencia, historia y examen inicial.",["hipótesis","probabilidad previa","prueba","resultado","probabilidad posterior"],["Definir qué harás con cada resultado.","Elegir pruebas estudiadas en poblaciones similares.","Evitar probar si no cambiará el plan."],["Baterías por rutina.","Interpretar sensibilidad como probabilidad individual.","Ignorar población y estándar."],["Si vale tiempo y provocación.","Qué umbral cambia conducta.","Qué incertidumbre persiste."],"Probabilidad previa baja de lesión grave y prueba inespecífica positiva interpretada como confirmación.","Explica por qué el valor predictivo puede ser bajo.","La exactitud depende de población, umbral, protocolo y diseño.","¿Cuándo aporta más una prueba?",["Cuando se aplica a todos.","Cuando puede cruzar un umbral de decisión.","Cuando es conocida.","Cuando reproduce dolor."],1,"La utilidad clínica se define por cuánto cambia probabilidad y conducta."),
      L("m8-l2","Sensibilidad, especificidad y razones de verosimilitud","Interpretación aplicada","Sensibilidad y especificidad describen rendimiento frente a un estándar. Las razones de verosimilitud actualizan probabilidad, pero calidad y aplicabilidad son esenciales.",["sensibilidad","especificidad","LR+","LR-","intervalo de confianza"],["Usar LR con probabilidad previa.","Revisar intervalos y sesgo.","Traducir cambio a acción."],["SnNout/SpPin absolutos.","Confundir p valor con exactitud.","Citar números sin protocolo."],["Si cambia suficiente la probabilidad.","Si se requiere otra prueba.","Cómo comunicar resultado."],"Prueba muy sensible y poco específica positiva en persona de baja probabilidad previa.","Explica por qué el positivo puede no confirmar.","Revisiones recientes muestran heterogeneidad y riesgo de sesgo incluso en pruebas populares.","¿Qué aporta una prueba muy sensible negativa?",["Confirma diagnóstico.","Puede reducir probabilidad si estudio y procedimiento son aplicables.","Descarta toda patología.","Obliga a imagen."],1,"Puede disminuir probabilidad, pero no es una regla universal."),
      L("m8-l3","Clusters, imagen y cierre prematuro","Convergencia sin dogma","Un cluster puede superar una prueba aislada si fue validado para una población concreta. La imagen debe responder una pregunta y cambiar manejo; muchos hallazgos son incidentales.",["cluster","imagen","diferencial","aplicabilidad","conducta"],["Verificar componentes y contexto.","Indicar imagen solo con pregunta defendible.","Mantener alternativas ante hallazgos comunes."],["Llamar cluster a cualquier combinación.","Imagen solo para tranquilizar.","Cerrar por degeneración."],["Si cambia tratamiento o derivación.","Cómo contextualizar hallazgos.","Qué explicación evita nocebo."],"Resonancia lumbar con cambios degenerativos en persona con mejoría funcional y sin señales de riesgo.","Redacta explicación contextualizada y decide si cambia plan.","NICE desaconseja imagen rutinaria en atención no especializada salvo sospecha de patología seria.","¿Qué justifica mejor una imagen?",["Dolor intenso.","Saber la estructura exacta.","Sospecha relevante o posibilidad real de cambiar manejo.","Persistencia por dos semanas."],2,"La imagen debe responder una pregunta clínica y modificar conducta." )
    ]),
    M("m9","Integración CIF, hipótesis, diagnóstico y pronóstico","Convertir datos en una representación del problema, prioridades y plan revisable centrado en función y participación.",[
      "Organizar hallazgos mediante CIF.","Diferenciar diagnóstico e hipótesis funcional.","Construir pronóstico con incertidumbre explícita."
    ],[
      L("m9-l1","CIF como mapa, no inventario","Funcionamiento y contexto","La CIF relaciona funciones y estructuras, actividades, participación y factores contextuales. Su valor está en mostrar interacciones y prioridades, no en llenar categorías.",["funciones","estructuras","actividades","participación","ambientales","personales"],["Identificar actividad prioritaria.","Vincular deficiencias modificables.","Reconocer facilitadores y barreras."],["Usar CIF como lista exhaustiva.","Tratar solo deficiencias.","Confundir factor personal con culpa."],["Qué dominio explica impacto.","Qué objetivo es modificable.","Qué recurso ambiental ayuda."],"Artrosis de rodilla, fuerza reducida, temor a caer y escaleras inaccesibles.","Construye mapa CIF y prioriza dos objetivos.","La rehabilitación prioriza independencia, participación y actividades significativas.","¿Qué representa mejor CIF?",["Dolor 6/10.","Artrosis grado 3.","Dolor y debilidad limitan escaleras y participación, influidos por temor y hogar.","Déficit de cuádriceps."],2,"Integra cuerpo, actividad, participación y contexto."),
      L("m9-l2","Representación del problema e hipótesis jerarquizadas","Síntesis clínica","Una representación resume persona, problema, tiempo, patrón, impacto, contexto y señales discriminativas. Las hipótesis se jerarquizan por riesgo, plausibilidad y capacidad de cambiar conducta.",["resumen","hipótesis principal","alternativas","a favor","en contra"],["Redactar una frase antes de etiquetar.","Mantener hipótesis de seguridad y mecanismo.","Buscar datos que refuten."],["Copiar toda la anamnesis.","Enamorarse de primera etiqueta.","Omitir evidencia en contra."],["Qué descartar primero.","Qué prueba discrimina.","Qué incertidumbre aceptar."],"Dolor lateral de cadera con sensibilidad, dolor al decúbito, debilidad y hallazgos lumbares coexistentes.","Jerarquiza tres hipótesis y pruebas discriminativas.","Los estudios de exactitud apoyan combinaciones específicas, pero la coexistencia y heterogeneidad exigen razonamiento iterativo.","¿Qué mejora una hipótesis?",["Explicar todo sin excepción.","Incluir evidencia a favor, en contra y forma de reevaluarla.","Etiqueta anatómica precisa.","Coincidir con imagen."],1,"Una hipótesis profesional es revisable y expuesta a refutación."),
      L("m9-l3","Pronóstico y plan revisable","Predicción prudente","El pronóstico combina trayectoria, función, salud, recursos, expectativas, demanda y respuesta inicial. Se comunica como rango condicionado, no promesa.",["pronóstico","favorables","barreras","plan","criterios de cambio"],["Explicitar factores.","Acordar ventana terapéutica.","Definir criterios de modificación."],["Plazos exactos sin base.","Imagen como destino.","Mantener plan sin resultados."],["Frecuencia inicial.","Qué se espera y cuándo.","Qué ausencia de progreso reabre hipótesis."],"Dolor lumbar persistente, buen apoyo, alta expectativa, baja actividad y tratamientos pasivos previos.","Formula pronóstico condicionado y plan de cuatro semanas.","Las guías recomiendan monitorizar progreso, educación, actividad y atención centrada en la persona.","¿Qué frase comunica mejor?",["Estará bien en cuatro semanas.","La resonancia indica recuperación lenta.","Hay factores favorables y barreras; probaremos y revisaremos función en dos semanas.","No se puede pronosticar."],2,"Comunica incertidumbre, factores y reevaluación sin prometer." )
    ]),
    M("m10","Seguimiento, resultados y cierre del razonamiento","Medir cambio relevante, revisar hipótesis y producir una síntesis útil para continuidad de cuidados.",[
      "Seleccionar resultados centrados en la persona.","Interpretar cambio, error y relevancia.","Cerrar con síntesis, plan y señales de revisión."
    ],[
      L("m10-l1","Dolor, función y resultados informados","PROMs con propósito","Los PROMs complementan entrevista y desempeño. Se eligen por dominio, propiedades de medición, carga y utilidad para decisiones.",["NRS","PSFS","cuestionario regional","calidad de vida","meta"],["Usar función específica y global cuando aporte.","Explicar para qué se mide.","Combinar puntaje, desempeño y percepción."],["Cuestionarios por rutina.","Interpretar todo cambio como real.","Usar solo dolor para alta."],["Qué dominio seguir.","Qué cambio importa.","Qué hacer ante discordancia."],"Dolor baja un punto, pero vuelve a trabajar y mejora cuatro puntos en actividad prioritaria.","Interpreta sin declarar éxito o fracaso solo por dolor.","Los conjuntos de resultados MSK incluyen dolor, desempeño, actividades, metas, calidad de vida, participación y afrontamiento.","¿Qué interpretación es más completa?",["No mejoró.","Mejoró en función relevante; deben integrarse dolor, meta, desempeño y percepción.","El cuestionario reemplaza entrevista.","El alta exige dolor cero."],1,"La recuperación es multidimensional y vinculada a metas."),
      L("m10-l2","Cambio detectable, relevancia y respuesta 24 horas","Reevaluación longitudinal","Un cambio puede reflejar error, variabilidad, aprendizaje o efecto real. Se interpreta con propiedades del instrumento, magnitud, coherencia y significado.",["línea basal","retest","SEM","MDC","MCID","respuesta diferida"],["Repetir en condiciones comparables.","Observar tendencia.","Integrar respuesta durante y después."],["Confundir MDC con importancia.","MCID como umbral individual rígido.","Cambiar por fluctuación aislada."],["Si supera variabilidad.","Si importa a la meta.","Si progresar o reducir carga."],"Fuerza aumenta 8%, pero el error del protocolo puede ser similar y el desempeño no cambia.","Define qué información falta antes de progresar.","La fiabilidad relativa puede ser buena mientras el error absoluto sigue siendo clínicamente importante.","¿Qué afirmación es correcta?",["ICC alto garantiza cambio real.","Interpretar con error absoluto, protocolo y función.","MCID es igual para todos.","Dos mediciones bastan."],1,"La fiabilidad relativa no elimina error absoluto ni define significado."),
      L("m10-l3","Síntesis final, derivación y aprendizaje continuo","Cerrar sin cerrar prematuramente","El cierre resume problema, seguridad, hipótesis, medidas, respuesta, decisión compartida, plan y criterios de alarma. También identifica qué debe revisar el clínico.",["síntesis","conducta","educación","derivación","seguimiento","reflexión"],["Redactar síntesis breve.","Entregar señales para consultar.","Programar reevaluación según riesgo."],["Copiar todos los datos.","Alta sin autogestión.","Ocultar incertidumbre."],["Alta, continuidad o derivación.","Qué comunicar a otro profesional.","Qué sesgo revisar."],"Tras cuatro semanas mejora función, pero aparece dolor nocturno nuevo y pérdida de peso involuntaria.","Actualiza la representación y define conducta.","La seguridad es longitudinal; nueva información puede reabrir hipótesis aunque exista mejoría parcial.","¿Qué conducta es más segura?",["Alta por mejoría funcional.","Mantener plan.","Actualizar riesgo y gestionar evaluación médica.","Agregar ejercicios."],2,"Las nuevas señales sistémicas cambian la prioridad." )
    ])
  ],
  references:[
    {citation:"Lin I, et al. What does best practice care for musculoskeletal pain look like? Eleven consistent recommendations from high-quality clinical practice guidelines. Br J Sports Med. 2020;54:79-86.",url:"https://pubmed.ncbi.nlm.nih.gov/30826805/"},
    {citation:"World Health Organization. WHO guideline for non-surgical management of chronic primary low back pain in adults. 2023.",url:"https://www.who.int/publications/i/item/9789240081789"},
    {citation:"World Health Organization. Package of interventions for rehabilitation: module 2, musculoskeletal conditions. 2023.",url:"https://www.who.int/publications/i/item/9789240071100/"},
    {citation:"Storari L, et al. Standardized Definition of Red Flags in Musculoskeletal Care: A Comprehensive Review of Clinical Practice Guidelines. Medicina. 2025;61:1002.",url:"https://pubmed.ncbi.nlm.nih.gov/40572690/"},
    {citation:"International IFOMPT Cervical Framework. J Orthop Sports Phys Ther. 2022.",url:"https://pubmed.ncbi.nlm.nih.gov/36099171/"},
    {citation:"Grenfell J, Soundy A. Shared Decision Making in Musculoskeletal Physiotherapy. Behav Sci. 2022;12:12.",url:"https://pubmed.ncbi.nlm.nih.gov/35049623/"},
    {citation:"Kosek E, et al. Chronic nociplastic pain affecting the musculoskeletal system: criteria and grading. Pain. 2021.",url:"https://pubmed.ncbi.nlm.nih.gov/33974577/"},
    {citation:"Waiteman MC, et al. Portable dynamometers for hip muscle strength. J Orthop Sports Phys Ther. 2023.",url:"https://pubmed.ncbi.nlm.nih.gov/37787581/"},
    {citation:"Espino RVS, et al. Hand-held dynamometers in lower-limb strength testing: systematic review and meta-analysis. 2026.",url:"https://pubmed.ncbi.nlm.nih.gov/42016044/"},
    {citation:"Kinsella R, et al. Diagnostic Accuracy of Clinical Tests for Greater Trochanteric Pain Syndrome. JOSPT. 2024.",url:"https://pubmed.ncbi.nlm.nih.gov/37561820/"},
    {citation:"Diagnostic accuracy of physical examination tests for painful cervical radiculopathy: systematic review update. 2026.",url:"https://pubmed.ncbi.nlm.nih.gov/41680685/"},
    {citation:"Developing and testing a consensus-based core set of outcome measures for musculoskeletal rehabilitation.",url:"https://pubmed.ncbi.nlm.nih.gov/28988517/"},
    {citation:"Fu W, et al. Educational Interventions to Develop Physical Therapist Clinical Reasoning. Phys Ther. 2025.",url:"https://pubmed.ncbi.nlm.nih.gov/39718199/"},
    {citation:"Ndacayisaba G, et al. Pedagogical tools to enhance clinical reasoning in physiotherapy. 2026.",url:"https://pubmed.ncbi.nlm.nih.gov/42046463/"},
    {citation:"Trumble E, et al. Distributed and retrieval practice in health professions education. 2024.",url:"https://pubmed.ncbi.nlm.nih.gov/37615780/"},
    {citation:"The Use of Virtual Patients to Provide Feedback on Clinical Reasoning. Acad Med. 2025.",url:"https://pubmed.ncbi.nlm.nih.gov/39485118/"},
    {citation:"Synthesis of guideline recommendations for primary care of chronic musculoskeletal pain. 2022.",url:"https://pubmed.ncbi.nlm.nih.gov/34913219/"},
    {citation:"NICE. Low back pain and sciatica: selective referral for imaging.",url:"https://www.nice.org.uk/guidance/qs155/chapter/Quality-statement-2-Referrals-for-imaging"}
  ]
};
