const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const clean=(v,max=1800)=>String(v??"").trim().slice(0,max);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fold=v=>clean(v,5000).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const has=(t,a)=>a.some(x=>t.includes(x)); const pts=a=>Math.min(4,a.filter(Boolean).length);
const refs={
1:{title:"Volver a agacharse",info:["7 meses","25 minutos","caminar","agach","temor"],twist:["doble","turno","dia siguiente"],adapt:["reduc","ajust","dosis","volumen","tiempo"],plan:["agach","recoger","10 minutos","reevalu","seguimiento"]},
2:{title:"Conducir y recuperar pausas",info:["45 minutos","90 minutos","turno","pausa","viaje"],twist:["test","rechaz","viaje"],adapt:["particip","trabajo","turno","indicador","pausa"],plan:["pausa","turno","viaje","tolerancia","reevalu"]},
3:{title:"El informe de imágenes",info:["10 meses","degener","imagen","escalera","temor"],twist:["garant","dolor","tarea"],adapt:["consent","negoci","toler","incertid","acord"],plan:["escalera","progres","toler","reevalu","seguimiento"]},
4:{title:"La dosis que no encaja",info:["6 meses","seis ejercicios","30 minutos","12 minutos","trabajo","clases"],twist:["todos los ejercicios","no pude ir","clases"],adapt:["reduc","prioriz","volumen","frecuencia","esfuerzo","dosis"],plan:["12 minutos","tres dias","una tarea","dosis","reevalu"]},
5:{title:"La pregunta que cambia la prioridad",info:["irradi","pierna","miccion","orinar","perine"],twist:["orinar","miccion","perine","entrepierna"],adapt:["urgenc","inmediata","deriv","medic","suspend","deten"],plan:["urgenc","inmediata","evaluacion medica","deriv","suspend","no ejercicio","no masaje"]}
};
function cmt(s,good,mid){return s>=4?good:s>=2?mid:"Falta explicitar datos concretos del caso y justificar la decisión clínica."}
function evaluate(id,a){const r=refs[id],x=Object.values(a).map(fold),i=x[0],s=x[1],n=x[2],p=x[3],o=x[4];
 const information=pts([has(i,r.info),has(i,["funcion","actividad","objetivo","particip"]),has(i,["hipotes","sintesis","decision","prioridad"]),has(i,["falta","incertid","corrobor","evaluar","preguntar"])]);
 const safety=id===5?pts([has(s,["miccion","orinar"]),has(s,["perine","entrepierna","silla de montar"]),has(s,["urgenc","inmediata","deriv","evaluacion medica"]),has(s,["suspend","deten","no continuar","no ejercicio","no masaje"])]):pts([has(s,["seguridad","bandera","trauma","fiebre","esfinter","neurolog","parestesia"]),has(s,["preguntar","corrobor","descartar","verificar"]),has(s,["continu","adapt","monitor","reevalu","suspend","deriv"]),has(s,["incertid","no asumir","no diagnost","falta"])]);
 const adaptation=pts([has(n,r.twist),has(n,r.adapt),has(n,["cambio","ajust","mantend","revis","decision"]),has(n,["reevalu","seguimiento","funcion","respuesta"])]);
 const plan=pts([has(p,r.plan),has(p,["objetivo","funcion","actividad","particip"]),id===5?has(p,["urgenc","medic","deriv","suspend"]):has(p,["dosis","frecuencia","repet","minuto","volumen","carga","pausa"]),has(p,["reevalu","seguimiento","control","respuesta","progres"])]);
 const reflection=pts([has(o,["fortaleza","bien","logre","positivo"]),has(o,["mejor","cambiar","debo","falt","repetiria"]),has(o,["pregunta","escucha","explic","seguridad","sintesis","objetivo","dosis"]),o.length>=40]);
 const total=information+safety+adaptation+plan+reflection;
 return {information:{score:information,comment:cmt(information,"Integras datos, función e incertidumbre en una síntesis útil.","Relaciona explícitamente dos datos concretos con tu decisión inicial.")},safety:{score:safety,comment:id===5?cmt(safety,"Reconoces los síntomas nuevos y priorizas evaluación médica inmediata sin continuar el plan habitual.","En este caso la seguridad precede al examen: explicita micción, sensibilidad perineal y conducta urgente."):cmt(safety,"Incorporas pesquisa de seguridad y una conducta proporcional.","Explicita qué dato de seguridad preguntarías y qué harías si apareciera.")},adaptation:{score:adaptation,comment:cmt(adaptation,"Usas el dato nuevo para revisar la decisión y el seguimiento.","Nombra el dato nuevo y explica exactamente qué decisión cambia.")},plan:{score:plan,comment:cmt(plan,"El plan se relaciona con la función e incluye conducta y reevaluación.",id===5?"Prioriza evaluación médica inmediata y suspende el plan habitual.":"Haz el objetivo más funcional y especifica dosis y reevaluación.")},reflection:{score:reflection,comment:cmt(reflection,"Transformas el feedback del observador en una acción concreta.","Separa fortaleza, mejora y conducta que repetirás distinto.")},total,level:total>=17?"Logrado":total>=13?"Adecuado con aspectos por profundizar":total>=9?"En desarrollo":"Requiere reforzar",strength:safety===Math.max(information,safety,adaptation,plan,reflection)?"Tu mejor desempeño estuvo en seguridad y priorización clínica.":"Tu respuesta contiene elementos útiles de razonamiento clínico.",improvement:id===5&&safety<4?"Prioriza la combinación de dificultad miccional y alteración perineal y comunica evaluación médica inmediata.":"Conecta cada decisión con un dato observable y deja claro qué reevaluarás.",nextStep:id===5?"Repite una explicación breve y no alarmista de por qué detienes el plan y coordinas evaluación médica.":"Repite usando: dato → interpretación provisional → decisión → indicador de reevaluación."};
}
function mail(rec){const f=rec.feedback,row=(l,x)=>'<tr><td style="padding:7px;border:1px solid #ddd"><b>'+esc(l)+'</b></td><td style="padding:7px;border:1px solid #ddd">'+x.score+'/4 · '+esc(x.comment)+'</td></tr>';
 return '<div style="font-family:Arial,sans-serif;color:#153a3f"><h2>KIN2002 · S1</h2><p><b>'+esc(rec.name)+'</b> · Caso '+String(rec.caseId).padStart(2,"0")+' '+esc(rec.caseTitle)+'<br>Código: '+esc(rec.id)+'</p><h3>Respuestas</h3><ol><li>'+esc(rec.answers.initialDecision)+'</li><li>'+esc(rec.answers.safety)+'</li><li>'+esc(rec.answers.newData)+'</li><li>'+esc(rec.answers.plan)+'</li><li>'+esc(rec.answers.observerFeedback)+'</li></ol><h3>Retroalimentación</h3><p><b>'+f.total+'/20 · '+esc(f.level)+'</b> (formativo, no nota)</p><table style="border-collapse:collapse;width:100%">'+row("Información",f.information)+row("Seguridad",f.safety)+row("Dato nuevo",f.adaptation)+row("Plan",f.plan)+row("Reflexión",f.reflection)+'</table><p><b>Fortaleza:</b> '+esc(f.strength)+'</p><p><b>A mejorar:</b> '+esc(f.improvement)+'</p><p><b>Próximo paso:</b> '+esc(f.nextStep)+'</p></div>';
}
export async function onRequestPost({request,env}){let b;try{b=await request.json()}catch{return json({error:"Solicitud inválida."},400)}
 if(b.website)return json({ok:true}); const name=clean(b.name,120),section=clean(b.section,4),caseId=Number(b.caseId),client=clean(b.clientSubmissionId,120),ref=refs[caseId],z=b.answers||{},a={initialDecision:clean(z.initialDecision),safety:clean(z.safety),newData:clean(z.newData),plan:clean(z.plan),observerFeedback:clean(z.observerFeedback)};
 if(section!=="S1"||!ref||b.role!=="kine"||name.length<3||!client||Object.values(a).some(v=>v.length<4))return json({error:"Completa nombre y las cinco respuestas."},400);
 if(!env.CERT_REQUESTS)return json({error:"El registro no está disponible. Tu borrador sigue en el dispositivo."},503);
 const id="K2-S1-"+String(caseId).padStart(2,"0")+"-"+client.slice(0,8).toUpperCase(),key="kin2002:"+client,old=await env.CERT_REQUESTS.get(key,"json");
 if(old?.feedback)return json({ok:true,id:old.id,feedback:old.feedback,emailSent:Boolean(old.emailSent),duplicate:true});
 let rec={id,clientSubmissionId:client,name,section,caseId,caseTitle:ref.title,answers:a,status:"saved",createdAt:new Date().toISOString(),emailSent:false};
 try{await env.CERT_REQUESTS.put(key,JSON.stringify(rec),{expirationTtl:15552000})}catch(e){console.error("save",e);return json({error:"No se pudo guardar. Tu borrador sigue en el dispositivo."},503)}
 rec={...rec,feedback:evaluate(caseId,a),status:"corrected",correctedAt:new Date().toISOString()}; await env.CERT_REQUESTS.put(key,JSON.stringify(rec),{expirationTtl:15552000});
 let emailSent=false,emailStatus="not_configured";
 if(env.RESEND_API_KEY){try{const rr=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:"Bearer "+env.RESEND_API_KEY,"content-type":"application/json","Idempotency-Key":"kin2002-"+client},body:JSON.stringify({from:"KineCheck <certificacion@kinecheck.cl>",to:["emmanuel.zuniga@docencia.uoh.cl","jmarceloma@gmail.com","constanzaa.correa@pregrado.uoh.cl"],subject:"[KIN2002] S1 · Caso "+String(caseId).padStart(2,"0")+" · "+name,html:mail(rec)})});emailSent=rr.ok;emailStatus=rr.ok?"sent":"delivery_failed"}catch(e){console.error("email",e);emailStatus="delivery_failed"}}
 rec={...rec,emailSent,emailStatus,status:emailSent?"notified":"saved_without_email",updatedAt:new Date().toISOString()}; await env.CERT_REQUESTS.put(key,JSON.stringify(rec),{expirationTtl:15552000});
 return json({ok:true,id,feedback:rec.feedback,emailSent,emailStatus});
}
export function onRequestGet(){return json({status:"ok",service:"kin2002-submit",flow:"save-first"});}
