const app=document.querySelector('#app');const scoreChip=document.querySelector('#score-chip');
const cases=[
{title:'Dolor lumbar con irradiación',level:'Intermedio',profile:'Hombre de 42 años, operador de maquinaria. Dolor lumbar de 10 días con irradiación posterior a muslo.',steps:[
{q:'¿Qué explorarías primero en la entrevista?',options:['Intensidad del dolor solamente','Síntomas neurológicos, mecanismo, evolución y banderas rojas','Preferencia de tratamiento','Pruebas de imagen previas'],correct:1,why:'Antes de asumir un cuadro mecánico hay que estimar seguridad, compromiso neurológico y comportamiento clínico.'},
{q:'Refiere adormecimiento en borde lateral del pie. ¿Qué examen priorizas?',options:['Palpación paravertebral','Screening neurológico: fuerza, sensibilidad y reflejos','Test de flexibilidad de isquiotibiales','Medición de perímetro de muslo'],correct:1,why:'El hallazgo orienta a compromiso neural y exige objetivar déficit neurológico.'},
{q:'Hay debilidad progresiva en flexión plantar y alteración esfinteriana reciente. ¿Conducta?',options:['Ejercicio graduado','Terapia manual y reevaluación en 7 días','Derivación médica urgente','Educación y autocuidado'],correct:2,why:'La combinación de déficit progresivo y síntomas esfinterianos obliga a descartar una urgencia neurológica.'}]},
{title:'Dolor de hombro relacionado con carga',level:'Principiante',profile:'Mujer de 35 años, profesora. Dolor anterolateral de hombro al elevar el brazo y al dormir sobre ese lado.',steps:[
{q:'¿Qué dato ayuda más a formular una hipótesis inicial?',options:['Color favorito','Relación carga-síntoma, evolución y limitación funcional','Estado civil','Dominancia manual solamente'],correct:1,why:'La relación entre carga, función y síntomas orienta mejor que una etiqueta estructural aislada.'},
{q:'¿Qué estrategia de examen es más coherente?',options:['Una prueba especial aislada','ROM, fuerza, respuesta a carga y tareas concordantes','Solicitar resonancia de inmediato','Palpación como único criterio'],correct:1,why:'La evaluación debe combinar capacidad, provocación concordante y función; una prueba aislada no establece causalidad.'},
{q:'No hay banderas rojas y la capacidad mejora al modificar la carga. ¿Plan inicial?',options:['Reposo absoluto','Educación, dosificación de carga y ejercicio progresivo','Cirugía inmediata','Inmovilización por seis semanas'],correct:1,why:'La modulación con carga apoya un manejo conservador centrado en exposición y recuperación progresiva.'}]},
{title:'Dolor persistente de rodilla',level:'Avanzado',profile:'Mujer de 58 años con dolor de rodilla de 2 años, temor al movimiento y reducción marcada de actividad.',steps:[
{q:'¿Qué marco de entrevista es más útil?',options:['Buscar una única estructura culpable','Explorar factores biológicos, psicológicos, sociales y funcionales','Evitar hablar de creencias','Preguntar solo la escala EVA'],correct:1,why:'En dolor persistente se requiere integrar contribuyentes múltiples y su impacto funcional.'},
{q:'Radiografía con cambios degenerativos moderados. ¿Cómo lo comunicas?',options:['La imagen explica completamente el dolor','La imagen no sirve para nada','Es un dato relevante, pero debe interpretarse junto a síntomas, función y contexto','Debe dejar de caminar'],correct:2,why:'Ni la sobreinterpretación ni la negación de la imagen son adecuadas; debe integrarse con la evaluación clínica.'},
{q:'¿Cuál es el objetivo inicial más razonable?',options:['Eliminar todo dolor antes de moverse','Aumentar gradualmente actividad y confianza con objetivos significativos','Evitar escaleras para siempre','Depender de tratamiento pasivo'],correct:1,why:'La recuperación funcional progresiva y la autoeficacia son ejes centrales en este perfil.'}]}
];
let state={caseIndex:null,step:0,answers:[],xp:Number(localStorage.getItem('kc_lab_xp')||0)};
function setXP(value){state.xp=value;localStorage.setItem('kc_lab_xp',String(value));scoreChip.textContent=`${value} XP`}
function home(){state.caseIndex=null;app.innerHTML=`<section class="hero"><span class="eyebrow">SIMULACIÓN CLÍNICA INTERACTIVA</span><h1>Entrena decisiones, no respuestas memorizadas.</h1><p>Practica entrevista, examen, seguridad clínica e intervención con casos breves y retroalimentación inmediata.</p><div class="actions"><button class="primary" id="start">Comenzar entrenamiento</button><button class="secondary" id="reset">Reiniciar progreso</button></div></section><section class="grid">${cases.map((c,i)=>`<article class="card"><span class="badge">${c.level}</span><h3>${c.title}</h3><p class="muted">${c.profile}</p><button class="secondary" data-case="${i}">Abrir caso</button></article>`).join('')}</section><p class="footer-note">Versión inicial de entrenamiento educativo. No sustituye evaluación clínica real ni protocolos locales de derivación.</p>`;document.querySelector('#start').onclick=()=>startCase(0);document.querySelector('#reset').onclick=()=>{setXP(0);home()};document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>startCase(Number(b.dataset.case)))}
function startCase(index){state.caseIndex=index;state.step=0;state.answers=[];renderStep()}
function renderStep(){const c=cases[state.caseIndex],s=c.steps[state.step],pct=Math.round((state.step/c.steps.length)*100);app.innerHTML=`<section class="panel"><div class="case-header"><div><span class="eyebrow">CASO ${state.caseIndex+1} · ${c.level.toUpperCase()}</span><h2>${c.title}</h2><p class="muted">${c.profile}</p></div><button class="secondary" id="exit">Salir</button></div><div class="progress"><span style="width:${pct}%"></span></div><h3>${state.step+1}. ${s.q}</h3><div class="choices">${s.options.map((o,i)=>`<button class="choice" data-option="${i}">${o}</button>`).join('')}</div><div id="feedback"></div></section>`;document.querySelector('#exit').onclick=home;document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.option),b))}
function answer(index,button){const c=cases[state.caseIndex],s=c.steps[state.step],correct=index===s.correct;document.querySelectorAll('[data-option]').forEach(b=>b.disabled=true);button.classList.add('selected');state.answers.push(correct);const feedback=document.querySelector('#feedback');feedback.className=`feedback ${correct?'good':'warn'}`;feedback.innerHTML=`<strong>${correct?'Decisión coherente':'Decisión mejorable'}</strong><p>${s.why}</p><button class="primary" id="next">${state.step===c.steps.length-1?'Ver resultados':'Continuar'}</button>`;document.querySelector('#next').onclick=()=>{state.step++;state.step>=c.steps.length?results():renderStep()}}
function results(){const c=cases[state.caseIndex],correct=state.answers.filter(Boolean).length,total=c.steps.length,percent=Math.round(correct/total*100),earned=correct*40+(correct===total?30:0);setXP(state.xp+earned);app.innerHTML=`<section class="panel"><span class="eyebrow">RETROALIMENTACIÓN</span><h2>${c.title}</h2><div class="score-grid"><div class="score-card"><strong>${percent}%</strong><span>desempeño</span></div><div class="score-card"><strong>${correct}/${total}</strong><span>decisiones coherentes</span></div><div class="score-card"><strong>+${earned}</strong><span>XP obtenido</span></div></div><div class="clinical-note"><strong>Lectura del desempeño</strong><p>${percent===100?'Muy buen razonamiento: priorizaste seguridad, coherencia clínica y función.':percent>=67?'Buen desempeño general. Revisa la decisión que omitió información clínica relevante.':'Conviene repetir el caso y priorizar seguridad, concordancia y contexto antes de intervenir.'}</p></div><div class="actions"><button class="primary" id="again">Repetir caso</button><button class="secondary" id="library">Elegir otro caso</button></div></section>`;document.querySelector('#again').onclick=()=>startCase(state.caseIndex);document.querySelector('#library').onclick=home}
setXP(state.xp);home();