begin;

create table if not exists public.platform_cases (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  workspace text not null default 'general'
    check (workspace in ('clinical','student','teaching','patient','general')),
  case_type text not null default 'clinical'
    check (case_type in ('clinical','student_practice','teaching','patient_followup','general')),
  title text not null check (char_length(title) between 1 and 180),
  status text not null default 'draft'
    check (status in ('draft','active','completed','archived')),
  progress smallint not null default 0
    check (progress between 0 and 100),
  current_step smallint not null default 1
    check (current_step between 1 and 20),
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_case_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.platform_cases(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 1 and 80),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.platform_user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_workspace text not null default 'general'
    check (active_workspace in ('clinical','student','teaching','patient','general')),
  theme text not null default 'system'
    check (theme in ('system','light','dark')),
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_feature_flags (
  key text primary key check (char_length(key) between 1 and 100),
  enabled boolean not null default false,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create or replace function public.platform_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create or replace function public.platform_log_case_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.platform_case_events (case_id, owner_id, event_type, payload)
  values (
    new.id,
    new.owner_id,
    case when tg_op = 'INSERT' then 'CASE_CREATED' else 'CASE_UPDATED' end,
    jsonb_build_object(
      'status', new.status,
      'progress', new.progress,
      'current_step', new.current_step,
      'workspace', new.workspace,
      'case_type', new.case_type
    )
  );
  return new;
end;
$$;

drop trigger if exists platform_cases_updated_at on public.platform_cases;
create trigger platform_cases_updated_at
before update on public.platform_cases
for each row execute function public.platform_set_updated_at();

drop trigger if exists platform_preferences_updated_at on public.platform_user_preferences;
create trigger platform_preferences_updated_at
before update on public.platform_user_preferences
for each row execute function public.platform_set_updated_at();

drop trigger if exists platform_cases_audit on public.platform_cases;
create trigger platform_cases_audit
after insert or update on public.platform_cases
for each row execute function public.platform_log_case_event();

create index if not exists platform_cases_owner_updated_idx
  on public.platform_cases (owner_id, updated_at desc);
create index if not exists platform_cases_owner_status_idx
  on public.platform_cases (owner_id, status, updated_at desc);
create index if not exists platform_case_events_case_idx
  on public.platform_case_events (case_id, created_at desc);

alter table public.platform_cases enable row level security;
alter table public.platform_case_events enable row level security;
alter table public.platform_user_preferences enable row level security;
alter table public.platform_feature_flags enable row level security;

drop policy if exists platform_cases_select_own on public.platform_cases;
create policy platform_cases_select_own
on public.platform_cases for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists platform_cases_insert_own on public.platform_cases;
create policy platform_cases_insert_own
on public.platform_cases for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists platform_cases_update_own on public.platform_cases;
create policy platform_cases_update_own
on public.platform_cases for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists platform_cases_delete_own on public.platform_cases;
create policy platform_cases_delete_own
on public.platform_cases for delete
to authenticated
using (owner_id = auth.uid());

drop policy if exists platform_case_events_select_own on public.platform_case_events;
create policy platform_case_events_select_own
on public.platform_case_events for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists platform_preferences_select_own on public.platform_user_preferences;
create policy platform_preferences_select_own
on public.platform_user_preferences for select
to authenticated
using (user_id = auth.uid());

drop policy if exists platform_preferences_insert_own on public.platform_user_preferences;
create policy platform_preferences_insert_own
on public.platform_user_preferences for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists platform_preferences_update_own on public.platform_user_preferences;
create policy platform_preferences_update_own
on public.platform_user_preferences for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists platform_flags_read_authenticated on public.platform_feature_flags;
create policy platform_flags_read_authenticated
on public.platform_feature_flags for select
to authenticated
using (true);

grant select, insert, update, delete on public.platform_cases to authenticated;
grant select on public.platform_case_events to authenticated;
grant select, insert, update on public.platform_user_preferences to authenticated;
grant select on public.platform_feature_flags to authenticated;
revoke all on public.platform_cases from anon;
revoke all on public.platform_case_events from anon;
revoke all on public.platform_user_preferences from anon;
revoke all on public.platform_feature_flags from anon;

revoke all on function public.platform_log_case_event() from public;
revoke all on function public.platform_set_updated_at() from public;

insert into public.platform_feature_flags (key, enabled, config)
values
  ('new_home', true, '{"version":"5.0"}'::jsonb),
  ('new_cases', true, '{"version":"1.0"}'::jsonb),
  ('new_library', true, '{"version":"1.0"}'::jsonb),
  ('student_tutor_v2', false, '{"stage":"foundation"}'::jsonb),
  ('teaching_studio_v1', false, '{"stage":"foundation"}'::jsonb),
  ('patient_experience_v2', false, '{"stage":"foundation"}'::jsonb)
on conflict (key) do update
set enabled = excluded.enabled,
    config = excluded.config,
    updated_at = now();

commit;
